import type { LanguageSettings } from "./types";

export const defaultMessages: Record<string, string> = {
  "dialog.ok": "OK",
  "dialog.cancel": "Cancel",
  "dialog.close": "Close",
  "dialog.apply": "Apply",
  "dialog.save": "Save",
  "dialog.reset": "Reset",
  "dialog.working": "Working...",
  "common.source": "source",
  "common.destination": "destination",
  "common.targets": "targets",
  "common.config": "config",
  "common.log": "log",
  "common.error": "error",
  "common.andMore": "...and {count} more",
  "common.on": "on",
  "common.off": "off",
  "common.yes": "yes",
  "common.no": "no",
  "shortcut.okEnter": "OK: Enter",
  "shortcut.cancelEsc": "Cancel: Esc",
  "shortcut.closeEnter": "Close: Enter",
  "shortcut.closeEsc": "Close: Esc",
  "shortcut.moveUpDown": "Move: Up/Down",
  "shortcut.showLeftRight": "Show: [ left / ] right",
  "shortcut.backEsc": "Back: Esc",
  "pane.filePanesAria": "File panes",
  "pane.quickFilterLabel": "filter:",
  "pane.quickFilterValue": "filter: {query}",
  "pane.quickFilterAria": "{title} quick filter",
  "pane.entriesAria": "{title} entries",
  "pane.filterReady": "filter ready",
  "pane.parentEntryEnabled": ".. enabled",
  "pane.loading": "Loading...",
  "pane.noEntries": "No entries",
  "pane.noFilterMatches": "No filter matches",
  "pane.meta": "{visible}/{total} items / {selected} selected{sort}{hidden}",
  "pane.metaFiltered": "{visible} shown / {matched} matched / {total} items / {selected} selected{kept}{sort}{hidden}",
  "pane.metaSort": " / sort:{sort}",
  "pane.metaHidden": " / hidden:on",
  "pane.metaKept": " / {count} kept",
  "pane.source.localFallback": "Local",
  "pane.source.loading": "Loading...",
  "pane.header.local": "Local: {label}",
  "pane.header.sftp": "SFTP: {label}",
  "pane.header.search": "Search: {label}",
  "pane.header.diff": "Diff: {label}",
  "pane.header.operationResult": "Result: {label}",
  "pane.header.gitStatus": "Git: {label}",
  "pane.header.archive": "Archive: {label}",
  "terminal.consoleAria": "Console",
  "terminal.ptyAria": "PTY terminal",
  "status.ready": "Ready.",
  "status.prefix": "prefix: {prefix}",
  "status.initializationFailed": "Initialization failed: {error}",
  "statusBar.active": "active",
  "statusBar.focus": "focus",
  "statusBar.focusConsole": "console",
  "statusBar.focusPane": "pane",
  "statusBar.console": "console",
  "statusBar.console.fullscreen": "fullscreen",
  "statusBar.console.starting": "starting",
  "statusBar.console.running": "running",
  "statusBar.console.ready": "ready",
  "statusBar.console.hidden": "hidden",
  "statusBar.command": "command",
  "statusBar.key": "key",
  "statusBar.selectMove": "select move",
  "navigation.rootLocalOnly": "Root navigation is only available for local panes.",
  "navigation.homeUnavailable": "Home directory is not available.",
  "navigation.homeLocalOnly": "Home navigation is only available for local panes.",
  "navigation.otherPanePathLocalOnly": "Opening the other pane path here is only available for local panes.",
  "navigation.currentPathOtherPaneLocalOnly": "Opening the current path in the other pane is only available for local panes.",
  "edit.localFilesOnly": "Editing is available for local files only.",
  "edit.filesOnly": "Editing is available for files only.",
  "edit.opened": "Opened text editor: {name}",
  "edit.failed": "Edit failed: {error}",
  "open.defaultApp": "Opened with OS default app: {name}",
  "open.failed": "Open failed: {error}",
  "open.virtualDefaultUnsupported": "Opening virtual entries with the OS default app is not implemented yet.",
  "viewer.openText": "Opened internal text viewer: {name}",
  "viewer.openImage": "Opened internal image viewer: {name}",
  "viewer.openImageFailed": "Image viewer failed: {error}",
  "viewer.sftpUnsupported": "SFTP file viewer is not implemented yet.",
  "clipboard.copyRejected": "Clipboard copy command was rejected.",
  "clipboard.copyFailed": "Clipboard copy failed.",
  "clipboard.copyFailedWithError": "Clipboard copy failed: {error}",
  "clipboard.pathsLocalOnly": "Clipboard path copy is available for local sources only.",
  "clipboard.noLocalPath": "No local path is available to copy.",
  "clipboard.pathsCopied": "Copied {count} path(s) to clipboard.",
  "clipboard.currentDirectoryLocalOnly": "Current directory copy is available for local sources only.",
  "clipboard.noCurrentDirectory": "No current directory is available to copy.",
  "clipboard.currentDirectoryCopied": "Copied current directory to clipboard.",
  "clipboard.namesLocalOnly": "Clipboard name copy is available for local sources only.",
  "clipboard.noLocalFilename": "No local filename is available to copy.",
  "clipboard.namesCopied": "Copied {count} filename(s) to clipboard.",
  "terminal.insertLocalOnly": "Terminal insertion is available for local sources only.",
  "terminal.noLocalPath": "No local path is available to insert.",
  "terminal.insertedPaths": "Inserted {count} path(s) into terminal.",
  "operation.sourceUnsupported": "This source/destination file operation is not implemented yet.",
  "search.truncated": "Search stopped at {count} item(s). Narrow the query to inspect more.",
  "search.truncatedPrompt": "Search stopped at {count} item(s). Press Enter to display or Esc to cancel.",
  "search.largePrompt": "Search found {count} item(s). Press Enter to display or Esc to cancel.",
  "search.sourceUnsupported": "Search source is available for local/archive/search panes in this phase.",
  "search.noRoot": "No local search root is available.",
  "search.largeCanceled": "Large search result display canceled.",
  "search.completed": "Search completed: {count} item(s).",
  "search.failed": "Search failed: {error}",
  "search.rootRequired": "root path is required",
  "search.field.minSize": "min size",
  "search.field.maxSize": "max size",
  "search.field.modifiedAfter": "modified after",
  "search.field.modifiedBefore": "modified before",
  "search.error.sizeRange": "min size must be less than or equal to max size",
  "search.error.dateRange": "modified after must be less than or equal to modified before",
  "search.error.nonNegativeSize": "{label} must be a non-negative value with optional K/M/G/T suffix",
  "search.error.sizeTooLarge": "{label} is too large",
  "search.error.dateFormat": "{label} must be YYYYMMDD",
  "search.error.dateInvalid": "{label} is invalid",
  "search.error.dateTooEarly": "{label} must be 1970-01-01 or later",
  "search.rootLabel": "Root",
  "git.localLikeOnly": "Git status is available for local-like panes only.",
  "git.changedFiles": "Git changed files: {count} item(s).",
  "git.failed": "Git status failed: {error}",
  "git.canceled": "Git status canceled.",
  "prefix.canceled": "Prefix canceled.",
  "prefix.noMatch": "No command for {prefix} {key}.",
  "operation.failureLogSaveFailed": "Operation failure log save failed: {error}",
  "operation.jobNotExecutable": "This job is not executable.",
  "operation.modeRequired": "Mode is required before execution.",
  "operation.attributesRequired": "Attribute expression is required before execution.",
  "operation.nameRequired": "Name is required before execution.",
  "operation.cancelAlreadyRequested": "Cancel already requested. Waiting for current item to finish.",
  "operation.cancelConfirmStatus": "Cancel operation? Enter stops after current item; Esc keeps running.",
  "operation.continues": "Operation continues.",
  "operation.cancelRequestedStatus": "Cancel requested. Waiting for current item to finish.",
  "operation.cancelNotAccepted": "Cancel request was not accepted.",
  "operation.cancelFailed": "Cancel request failed: {error}",
  "operation.noUndo": "No undoable operation.",
  "operation.noRedo": "No redoable operation.",
  "operation.undoStatus": "{label} ({undo} undo / {redo} redo)",
  "operation.redoStatus": "{label} ({undo} undo / {redo} redo)",
  "operation.failureVirtualFolder": "Operation failure virtual folder: {count} item(s).",
  "location.activeSftpLoadFailed": "Active SFTP session load failed: {error}",
  "location.sftpSessionDisconnected": "SFTP session disconnected: {connectionId}",
  "location.sftpSessionDisconnectFailed": "SFTP session disconnect failed: {error}",
  "location.alreadyLocal": "Already on a local source.",
  "location.searchProfileOnly": "Only search sources can be saved as search profiles.",
  "location.searchProfileDuplicate": "Search profile already exists: {name}",
  "location.searchProfileAdded": "Search profile added: {name}",
  "location.searchProfileAddFailed": "Search profile add failed: {error}",
  "location.localFavoriteOnly": "Only local paths can be added to favorites.",
  "location.localFavoriteDuplicate": "Local favorite already exists: {path}",
  "location.localFavoriteAdded": "Local favorite added: {name}",
  "location.localFavoriteAddFailed": "Local favorite add failed: {error}",
  "location.sftpProfileSavedWithCount": "SFTP profile saved: {name} ({count} profile(s))",
  "location.sftpProfileSaved": "SFTP profile saved: {name}",
  "location.sftpProfileSaveFailed": "SFTP profile save failed: {error}",
  "location.selectSftpProfileBeforeDelete": "Select an SFTP profile before deleting.",
  "location.confirmDeleteSftpProfileStatus": "Press D again or Enter to delete SFTP profile: {name}",
  "location.sftpProfileDeleted": "SFTP profile deleted: {name}",
  "location.sftpProfileDeleteFailed": "SFTP profile delete failed: {error}",
  "location.selectActiveSftpBeforeDisconnect": "Select an active SFTP session before disconnecting.",
  "location.confirmDeleteLocalFavoriteStatus": "Press D again or Enter to delete local favorite: {name}",
  "location.localFavoriteDeleted": "Local favorite deleted: {name}",
  "location.localFavoriteDeleteFailed": "Local favorite delete failed: {error}",
  "location.confirmDeleteSearchProfileStatus": "Press D again or Enter to delete search profile: {name}",
  "location.searchProfileDeleted": "Search profile deleted: {name}",
  "location.searchProfileDeleteFailed": "Search profile delete failed: {error}",
  "location.profileSavedAfterConnection": "{message} Profile saved.",
  "location.profileSaveFailedAfterConnection": "{message} Profile save failed: {error}",
  "location.profileSaveFailedInline": "Profile save failed: {error}",
  "location.sftpConnectionSucceeded": "SFTP connection succeeded.",
  "location.sftpUnknownHostKeyStatus": "SFTP host key is unknown: {host}:{port}",
  "location.sftpConnectionFailed": "SFTP connection failed: {error}",
  "location.status.trustingHostKey": "trusting host key...",
  "location.status.hostKeyNotRegistered": "host key is not registered",
  "location.status.hostKeyTrustCanceled": "host key trust canceled",
  "location.validation.hostRequired": "host is required",
  "location.validation.portRange": "port must be 1-65535",
  "location.validation.usernameRequired": "username is required",
  "location.validation.passwordRequired": "password is required",
  "location.validation.privateKeyPathRequired": "private key path is required",
  "location.validation.profileNameRequiredWhenSaving": "profile name is required when saving",
  "location.validation.profileNameRequired": "profile name is required",
  "location.rootLabel": "Root",
  "location.option.local": "<Local>",
  "location.option.root": "<Root>",
  "location.option.home": "<Home>",
  "location.option.newSftp": "<New SFTP Connection>",
  "location.option.localCurrent": "stay on current local source",
  "location.option.returnToLocal": "return to {path}",
  "location.option.homeUnresolved": "(home unresolved)",
  "location.option.newSftpDetail": "create or test an SFTP profile",
  "location.option.searchDetail": "search:{rootPath} [{query}{recursiveSuffix}]",
  "location.option.searchRecursiveSuffix": ", recursive",
  "location.option.sftpProfileDetail": "{username}@{host}:{port}{remotePath} ({authKind})",
  "terminal.copyModeStatus": "Terminal copy mode: move to select, Enter copies, Esc cancels.",
  "terminal.copyModeNoSelection": "No terminal text is selected.",
  "terminal.copyModeCopied": "Copied terminal selection.",
  "terminal.copyModeCopyFailed": "Terminal text copy failed.",
  "terminal.copyModeCopyFailedWithError": "Terminal text copy failed: {error}",
  "terminal.copyModeCancelled": "Terminal copy mode cancelled.",
  "terminal.startFailed": "[terminal start failed] {error}",
  "terminal.unavailable": "[terminal unavailable] {error}",
  "terminal.shellExited": "[shell exited: {code}] Press x to restart.",
  "terminal.initialPrompt": "Terminal not started. Press x to focus and start the shell.",
  "operationResult.diffUnsupported": "Diff virtual folder is available for local/search/diff panes only.",
  "operationResult.diffVirtualFolder": "Diff virtual folder: {side} pane, {count} item(s).",
  "operationResult.sourceCount": "{count} failed item(s)",
  "operationResult.sourceLabel": "operation failed: {label} ({countLabel})",
  "properties.noEntry": "No entry for properties.",
  "properties.status": "Properties: {count} item(s).",
  "diff.statusSummary": "Pane diff: {changed} changed / {identical} identical.",
  "diff.detailedAlreadyRunning": "Detailed diff is already running. Press Esc to cancel.",
  "diff.detailedLocalOnly": "Detailed diff is available for local panes only.",
  "diff.detailedRequiresBothPaths": "Detailed diff requires both pane paths.",
  "diff.detailedScanning": "Detailed diff: scanning recursively and calculating MD5... Press Esc to cancel.",
  "diff.detailedStatusSummary": "Detailed diff: {changed} changed / {identical} identical.",
  "diff.detailedCanceled": "Detailed diff canceled.",
  "diff.detailedCanceledError": "Detailed diff canceled",
  "diff.detailedFailed": "Detailed diff failed: {error}",
  "diff.detailedCancelRequested": "Detailed diff cancel requested...",
  "diff.detailedCancelNotAccepted": "Detailed diff cancel request was not accepted.",
  "diff.detailedCancelFailed": "Detailed diff cancel failed: {error}",
  "diff.sourceSide.left": "left",
  "diff.sourceSide.right": "right",
  "diff.sourceCount": "{count} item(s)",
  "diff.sourceLabel": "{side} diff: {label} ({countLabel})",
  "operation.confirmTitle": "Confirm {label}",
  "operation.failedTitle": "{label} Failed",
  "operation.executing": "Executing...",
  "operation.cancelConfirm": "Cancel operation?",
  "operation.cancelRequested": "Cancel requested",
  "operation.stopEnter": "Stop: Enter",
  "operation.keepRunningEsc": "Keep running: Esc",
  "operation.undoCheck": "Undo check",
  "operation.failedCount": "{count} failed",
  "operation.resultSummary": "{succeeded} succeeded / {failed} failed",
  "operation.resultStatus": "{label}: {succeeded} succeeded / {failed} failed",
  "operation.resultCanceledLabel": "{label} canceled",
  "operation.resultLogSuffix": " / log: {path}",
  "operation.terminalFailed": "[failed] {path}: {message}",
  "operation.terminalOk": "[ok] {path}: {message}",
  "operation.terminalOkMore": "[ok] ...and {count} more",
  "operation.terminalSummary": "[operation] {status}",
  "operation.resultMessage.sftpOperationUnsupported": "This SFTP file operation is not implemented yet.",
  "operation.resultMessage.refreshCompleted": "Refresh completed.",
  "operation.resultMessage.sftpToSftpCopyUnsupported": "SFTP to SFTP copy is not implemented yet.",
  "operation.resultMessage.sftpCopyRequiresMixedSources": "SFTP copy requires a local/SFTP source and destination.",
  "operation.resultMessage.targetNotSftpPath": "Target is not an SFTP path.",
  "operation.resultMessage.mixedSftpCopyUnsupported": "Mixed SFTP connections in one copy job are not supported.",
  "operation.resultMessage.sftpTargetMissingFileName": "SFTP target has no file name.",
  "operation.resultMessage.localTargetMissingFileName": "Local target has no file name.",
  "operation.resultMessage.sftpDeleteRequiresTargets": "SFTP delete requires SFTP targets.",
  "operation.resultMessage.mixedSftpDeleteUnsupported": "Mixed SFTP connections in one delete job are not supported.",
  "operation.resultMessage.deletedFromSftp": "Deleted permanently from SFTP.",
  "operation.resultMessage.noTargetResolved": "No target was resolved.",
  "operation.resultMessage.sftpTargetMissingParent": "SFTP target has no parent directory.",
  "operation.resultMessage.requestedNameIsCurrent": "Requested name is the current name.",
  "operation.resultMessage.sftpMkdirRequiresDestination": "SFTP mkdir requires an SFTP destination.",
  "operation.resultMessage.destinationExists": "Destination already exists.",
  "operation.resultMessage.sftpDirectoryCreated": "Directory created on SFTP.",
  "operation.resultMessage.sftpCreateFileRequiresDestination": "SFTP file creation requires an SFTP destination.",
  "operation.resultMessage.sftpFileCreated": "File created on SFTP.",
  "operation.resultMessage.sftpChmodRequiresTargets": "SFTP chmod requires SFTP targets.",
  "operation.resultMessage.mixedSftpChmodUnsupported": "Mixed SFTP connections in one chmod job are not supported.",
  "operation.resultMessage.sftpEmptyDirectoryRemoved": "Removed empty SFTP directory.",
  "operation.resultMessage.undoRequiresEmptySftpFile": "Undo can remove only an empty SFTP file.",
  "operation.resultMessage.sftpEmptyFileRemoved": "Removed empty SFTP file.",
  "operation.resultMessage.targetMissingParent": "Target has no parent directory.",
  "operation.resultMessage.windowsAttributesChanged": "Changed Windows attributes.",
  "operation.resultMessage.deletedPermanently": "Deleted permanently.",
  "operation.resultMessage.movedToTrash": "Moved to Trash.",
  "operation.resultMessage.directoryCreated": "Directory created.",
  "operation.resultMessage.fileCreated": "File created.",
  "operation.resultMessage.emptyDirectoryRemoved": "Removed empty directory.",
  "operation.resultMessage.undoRequiresEmptyFile": "Undo can remove only an empty file.",
  "operation.resultMessage.emptyFileRemoved": "Removed empty file.",
  "operation.resultMessage.noArchiveSources": "No archive sources were resolved.",
  "operation.resultMessage.archiveExtensionRequired": "Archive name must end with .zip, .tar, .tar.gz, or .tgz.",
  "operation.resultMessage.archiveInsideSource": "Cannot create an archive inside a selected source directory.",
  "operation.resultMessage.archiveLinksNotAllowed": "Archive links are not allowed for extraction.",
  "operation.resultMessage.archiveSpecialEntriesNotAllowed": "Archive special entries are not allowed for extraction.",
  "operation.resultMessage.archiveEntryPathEmpty": "Archive entry path is empty.",
  "operation.resultMessage.archiveCreationCanceled": "Archive creation canceled.",
  "operation.resultMessage.archiveExtractionCanceled": "Archive extraction canceled.",
  "operation.resultMessage.archiveExtractionEntryLimit": "Archive extraction exceeded the 100,000 entry limit.",
  "operation.resultMessage.archiveExtractionSizeLimit": "Archive extraction exceeded the 64 GiB expanded size limit.",
  "operation.resultMessage.archiveListingLimit": "Archive listing exceeded the 100,000 entry limit.",
  "operation.resultMessage.directoryListingLimit": "Directory listing exceeded the 100,000 entry limit.",
  "operation.resultMessage.sftpListingLimit": "SFTP listing exceeded the 100,000 entry limit.",
  "operation.resultMessage.detailedDiffCanceled": "Detailed diff canceled.",
  "operation.resultMessage.searchSizeRange": "Search min size must be less than or equal to max size",
  "operation.resultMessage.searchDateRange": "Search modified-after must be less than or equal to modified-before",
  "operation.resultMessage.unsupportedSearchKind": "Unsupported search kind.",
  "operation.resultMessage.unsupportedHiddenSearchMode": "Unsupported hidden search mode.",
  "operation.resultMessage.unsupportedReadonlySearchMode": "Unsupported readonly search mode.",
  "operation.resultMessage.sftpHostRequired": "SFTP host is required.",
  "operation.resultMessage.sftpPortRange": "SFTP port must be between 1 and 65535.",
  "operation.resultMessage.sftpUsernameRequired": "SFTP username is required.",
  "operation.resultMessage.sftpPasswordRequired": "SFTP password is required.",
  "operation.resultMessage.sftpPrivateKeyRequired": "SFTP private key path is required.",
  "operation.resultMessage.unsupportedSftpAuth": "Unsupported SFTP authentication kind.",
  "operation.resultMessage.sftpConnectionStateUnavailable": "SFTP connection state is unavailable.",
  "operation.resultMessage.sshHostKeyUnknown": "SSH server host key type is unknown.",
  "operation.resultMessage.sshHostKeyUnavailable": "SSH server host key is unavailable.",
  "operation.resultMessage.terminalNotRunning": "Terminal is not running.",
  "operation.resultMessage.terminalStateLockPoisoned": "Terminal state lock poisoned.",
  "operation.resultMessage.safeModeStateLockFailed": "Safe Mode state lock failed.",
  "operation.resultMessage.homeDirectoryUnresolved": "Home directory could not be resolved.",
  "operation.resultMessage.homeDirectoryUnresolvedForKnownHosts": "Home directory could not be resolved for known_hosts.",
  "operation.resultMessage.configDirectoryUnresolved": "Config directory could not be resolved.",
  "operation.resultMessage.sftpUploadSymlinkUnsupported": "Uploading symlinks to SFTP is not implemented yet.",
  "operation.resultMessage.pathEmpty": "Path is empty.",
  "operation.resultMessage.destinationPathNotSet": "Destination path is not set.",
  "operation.resultMessage.nameNotSet": "Name is not set.",
  "operation.resultMessage.modeNotSet": "Mode is not set.",
  "operation.resultMessage.windowsAttributeExpressionNotSet": "Windows attribute expression is not set.",
  "operation.resultMessage.modeOctalRequired": "Mode must be an octal value like 644, 755, or 0755.",
  "operation.resultMessage.noWindowsAttributeChanges": "No Windows attribute changes were requested.",
  "operation.resultMessage.windowsAttributeValues": "Attribute values must be on, off, or keep.",
  "operation.resultMessage.supportedWindowsAttributes": "Supported Windows attributes are readonly/r and hidden/h.",
  "operation.resultMessage.namePathSeparators": "Name must not contain path separators.",
  "operation.resultMessage.nameNul": "Name must not contain NUL characters.",
  "operation.resultMessage.nameInvalidWindows": "Name contains characters that are invalid on Windows.",
  "operation.resultMessage.nameReservedWindows": "Name is reserved on Windows.",
  "operation.resultMessage.nameTrailingWindows": "Name must not end with a space or period on Windows.",
  "operation.resultMessage.searchProfileNameRequired": "Search profile name is required.",
  "operation.resultMessage.localFavoriteNameRequired": "Local favorite name is required.",
  "operation.resultMessage.sftpProfileNameRequired": "SFTP profile name is required.",
  "operation.resultMessage.sftpProfileIdRequired": "SFTP profile id is required.",
  "operation.resultMessage.localFavoriteIdRequired": "Local favorite id is required.",
  "operation.resultMessage.searchProfileIdRequired": "Search profile id is required.",
  "operation.resultMessage.externalCommandIdRequired": "External command id is required.",
  "operation.resultMessage.textEditorNotConfigured": "Text editor is not configured. Register it from Settings > Text Editor.",
  "operation.resultMessage.archiveEntryMissingFileName": "Archive entry has no file name.",
  "operation.resultMessage.copiedTo": "Copied to '{destination}'.",
  "operation.resultMessage.movedTo": "Moved to '{destination}'.",
  "operation.resultMessage.renamedTo": "Renamed to '{destination}'.",
  "operation.resultMessage.downloadedTo": "Downloaded to '{destination}'.",
  "operation.resultMessage.uploadedTo": "Uploaded to '{destination}'.",
  "operation.resultMessage.extractedTo": "Extracted to '{destination}'.",
  "operation.resultMessage.destinationExistsAt": "Destination already exists: '{destination}'",
  "operation.resultMessage.modeChanged": "Changed mode to {mode}.",
  "operation.resultMessage.remoteModeChanged": "Changed remote mode to {mode}.",
  "operation.resultMessage.archiveCreated": "Archive created with {count} item(s).",
  "operation.resultMessage.sftpConnectionBusy": "SFTP connection is busy or unavailable: {connectionId}",
  "operation.resultMessage.sftpConnectionUnavailable": "SFTP connection is not available: {connectionId}",
  "operation.resultMessage.sftpSubsystemFailed": "Start SFTP subsystem failed: {error}",
  "operation.resultMessage.renameSftpEntryFailed": "Rename SFTP entry failed for '{path}': {error}",
  "operation.resultMessage.changeSftpModeFailed": "Change SFTP mode failed for '{path}': {error}",
  "operation.resultMessage.deleteSftpFileFailed": "Delete SFTP file failed for '{path}': {error}",
  "operation.resultMessage.createSftpDirectoryFailed": "Create SFTP directory failed: {error}",
  "operation.resultMessage.createSftpFileFailed": "Create SFTP file failed: {error}",
  "operation.resultMessage.removeEmptySftpDirectoryFailed": "Remove empty SFTP directory failed for '{path}': {error}",
  "operation.resultMessage.removeEmptySftpFileFailed": "Remove empty SFTP file failed for '{path}': {error}",
  "operation.resultMessage.readSftpMetadataFailed": "Read SFTP metadata failed for '{path}': {error}",
  "operation.resultMessage.readSftpDirectoryFailed": "Read SFTP directory failed for '{path}': {error}",
  "operation.resultMessage.openSftpFileFailed": "Open SFTP file failed for '{path}': {error}",
  "operation.resultMessage.finalizeSftpPartFileFailed": "Finalize SFTP part file failed for '{path}': {error}",
  "operation.resultMessage.removeSftpDirectoryFailed": "Remove SFTP directory failed for '{path}': {error}",
  "operation.resultMessage.moveToTrashFailed": "Move to Trash failed for '{path}': {error}",
  "operation.resultMessage.readArchiveFailed": "Read archive failed: {error}",
  "operation.resultMessage.readArchiveEntriesFailed": "Read archive entries failed: {error}",
  "operation.resultMessage.readArchiveEntryFailed": "Read archive entry failed: {error}",
  "operation.resultMessage.readArchiveEntryPathFailed": "Read archive entry path failed: {error}",
  "operation.resultMessage.readArchiveEntryBytesFailed": "Read archive entry bytes failed: {error}",
  "operation.resultMessage.finishZipArchiveFailed": "Finish zip archive failed: {error}",
  "operation.resultMessage.finishTarGzArchiveFailed": "Finish tar.gz archive failed: {error}",
  "operation.resultMessage.finishGzipStreamFailed": "Finish gzip stream failed: {error}",
  "operation.resultMessage.finishTarEntriesFailed": "Finish tar entries failed: {error}",
  "operation.resultMessage.openPtyFailed": "Open PTY failed: {error}",
  "operation.resultMessage.spawnShellFailed": "Spawn shell failed: {error}",
  "operation.resultMessage.writeTerminalFailed": "Write terminal failed: {error}",
  "operation.resultMessage.imageReaderTaskFailed": "Image reader task failed: {error}",
  "operation.resultMessage.textViewerTaskFailed": "Text viewer task failed: {error}",
  "operation.resultMessage.noSocketAddress": "No socket address resolved for {host}:{port}",
  "operation.resultMessage.unsupportedArchiveType": "Unsupported archive type: '{path}'",
  "operation.resultMessage.notTarArchive": "Not a tar archive: '{path}'",
  "operation.resultMessage.destinationMissingFileName": "Destination has no file name: '{path}'",
  "operation.resultMessage.archiveSourceMissingFileName": "Archive source has no file name: '{path}'",
  "operation.resultMessage.archiveDestinationMissingParent": "Archive destination has no parent: '{path}'",
  "operation.resultMessage.archiveDestinationParentUnresolved": "Archive destination parent cannot be resolved: '{path}'",
  "operation.resultMessage.sourceMissingFileName": "Source has no file name: '{path}'",
  "operation.resultMessage.destinationMissingParentPath": "Destination has no parent: '{path}'",
  "operation.resultMessage.archiveUnsafePath": "Archive entry has an unsafe path: '{path}'",
  "operation.resultMessage.archiveEntryDirectory": "Archive entry is a directory: {path}",
  "operation.resultMessage.invalidNameRegex": "Invalid name regex: {error}",
  "operation.resultMessage.sftpProfileNotFound": "SFTP profile was not found: {id}",
  "operation.resultMessage.localFavoriteNotFound": "Local favorite was not found: {id}",
  "operation.resultMessage.searchProfileNotFound": "Search profile was not found: {id}",
  "operation.resultMessage.invalidArchiveEntryPath": "Invalid archive entry path: {path}",
  "operation.resultMessage.unsupportedImageExtension": "Unsupported image extension: .{extension}",
  "operation.resultMessage.notRegularFile": "Not a regular file: '{path}'",
  "operation.resultMessage.unknownLanguagePreset": "Unknown language preset: {locale}",
  "operation.resultMessage.temporaryArchiveExists": "Temporary archive already exists: '{path}'",
  "operation.resultMessage.sftpPartFileExists": "SFTP part file already exists: '{path}'",
  "operation.resultMessage.extractedDestinationExists": "Extracted destination already exists: '{path}'",
  "operation.resultMessage.archiveEntryNotFound": "Archive entry was not found: '{archive}::/{path}'",
  "operation.resultMessage.textEditorTargetMustBeFile": "Text editor target must be a local file: {path}",
  "operation.resultMessage.pathMustResolveToAbsolute": "Path must resolve to a local absolute path: {path}",
  "operation.resultMessage.searchRootNotDirectory": "Search root is not a directory: {path}",
  "operation.resultMessage.localFavoritePathNotDirectory": "Local favorite path is not a directory: {path}",
  "operation.resultMessage.gitRootUnresolved": "Git root could not be resolved for {path}.",
  "operation.resultMessage.gitCommandFailed": "{command} failed.",
  "operation.resultMessage.gitCommandFailedWithMessage": "{command} failed: {error}",
  "operation.resultMessage.diffRootMissing": "{label} path does not exist: {path}",
  "operation.resultMessage.diffRootNotDirectory": "{label} path is not a directory: {path}",
  "operation.resultMessage.terminalCwdNotDirectory": "Terminal cwd is not a directory: '{path}'",
  "operation.resultMessage.externalCommandNameRequired": "External command name is required: {id}",
  "operation.resultMessage.externalCommandTemplateRequired": "External command template is required: {id}",
  "operation.resultMessage.externalCommandArgumentMode": "External command argumentMode must be args, repeat, or join: {id}",
  "operation.resultMessage.safeModeStartupFailed": "Safe Mode startup failed: {error}",
  "operation.resultMessage.sftpPrivateKeyPathRequiredFor": "{label} private key path is required.",
  "operation.resultMessage.sftpPrivateKeyFileMissing": "{label} private key file does not exist: {path}",
  "operation.resultMessage.sftpPrivateKeyAuthFailed": "{label} private key authentication failed: {error}",
  "operation.resultMessage.sftpPasswordAuthFailed": "{label} password authentication failed: {error}",
  "operation.resultMessage.sftpAuthFailed": "{label} authentication failed.",
  "operation.resultMessage.sshHostKeyMismatch": "SSH host key mismatch for {host}:{port}. Check {path} before connecting.",
  "operation.resultMessage.sshKnownHostsCheckFailed": "SSH known_hosts check failed for {host}:{port} using {path}.",
  "operation.resultMessage.sshKnownHostsReadFailed": "Read SSH known_hosts failed ({path}): {error}",
  "operation.resultMessage.sshKnownHostsDirectoryFailed": "Create SSH known_hosts directory failed ({path}): {error}",
  "operation.resultMessage.sshKnownHostsWriteFailed": "Write SSH known_hosts failed ({path}): {error}",
  "operation.resultMessage.sftpConnectHostFailed": "Connect to SFTP host failed for {host}:{port}. Tried: {tried}",
  "operation.resultMessage.createSshSessionFailed": "Create SSH session failed: {error}",
  "operation.resultMessage.resolveSftpHostFailed": "Resolve SFTP host failed: {error}",
  "operation.resultMessage.openSshKnownHostsStoreFailed": "Open SSH known_hosts store failed: {error}",
  "operation.resultMessage.readSftpDirectoryPlainFailed": "Read SFTP directory failed: {error}",
  "operation.resultMessage.parseLocationProfilesFailed": "Parse location profiles failed: {error}",
  "operation.resultMessage.serializeLocationProfilesFailed": "Serialize location profiles failed: {error}",
  "operation.resultMessage.parseExternalCommandsFailed": "Parse external commands failed: {error}",
  "operation.resultMessage.serializeExternalCommandsFailed": "Serialize external commands failed: {error}",
  "operation.resultMessage.parseSettingsFailed": "Parse settings failed: {error}",
  "operation.resultMessage.serializeSettingsFailed": "Serialize settings failed: {error}",
  "operation.resultMessage.parseLanguagePresetFailed": "Parse {language} language preset failed: {error}",
  "operation.resultMessage.parseNamedSettingsFailed": "Parse {label} failed: {error}",
  "operation.resultMessage.serializeNamedSettingsFailed": "Serialize {label} failed: {error}",
  "operation.resultMessage.readDirectoryEntryFailed": "Failed to read directory entry: {error}",
  "operation.resultMessage.failedToPath": "Failed to {action} '{path}': {error}",
  "operation.resultMessage.actionFailedForPath": "{action} failed for '{path}': {error}",
  "operation.resultMessage.actionFailed": "{action} failed: {error}",
  "operation.errorAction.addZipDirectory": "add zip directory",
  "operation.errorAction.addZipFile": "add zip file",
  "operation.errorAction.appendTarDirectory": "append tar directory",
  "operation.errorAction.appendTarFile": "append tar file",
  "operation.errorAction.changeHiddenAttribute": "change hidden attribute",
  "operation.errorAction.changePermissions": "change permissions",
  "operation.errorAction.changeReadonlyAttribute": "change readonly attribute",
  "operation.errorAction.changeSftpMode": "change SFTP mode",
  "operation.errorAction.clonePtyReader": "clone PTY reader",
  "operation.errorAction.createSshSession": "create SSH session",
  "operation.errorAction.createArchive": "create archive",
  "operation.errorAction.createCopyDestination": "create copy destination",
  "operation.errorAction.createDirectory": "create directory",
  "operation.errorAction.createDirectorySymlink": "create directory symlink",
  "operation.errorAction.createDownloadDirectory": "create download directory",
  "operation.errorAction.createDownloadParentDirectory": "create download parent directory",
  "operation.errorAction.createDownloadedFile": "create downloaded file",
  "operation.errorAction.createSftpDirectory": "create SFTP directory",
  "operation.errorAction.createSftpFile": "create SFTP file",
  "operation.errorAction.createExtractedDirectory": "create extracted directory",
  "operation.errorAction.createExtractedFile": "create extracted file",
  "operation.errorAction.createExtractedParentDirectory": "create extracted parent directory",
  "operation.errorAction.createExtractionDirectory": "create extraction directory",
  "operation.errorAction.createFile": "create file",
  "operation.errorAction.createFileSymlink": "create file symlink",
  "operation.errorAction.createSymlink": "create symlink",
  "operation.errorAction.delete": "delete",
  "operation.errorAction.deleteSftpFile": "delete SFTP file",
  "operation.errorAction.detailedDiffTask": "detailed diff task",
  "operation.errorAction.directoryListingTask": "directory listing task",
  "operation.errorAction.archiveListingTask": "archive listing task",
  "operation.errorAction.fileOperationTask": "file operation task",
  "operation.errorAction.finishArchive": "finish archive",
  "operation.errorAction.finishGzipStream": "finish gzip stream",
  "operation.errorAction.finishTarEntries": "finish tar entries",
  "operation.errorAction.finishTarGzArchive": "finish tar.gz archive",
  "operation.errorAction.finishZipArchive": "finish zip archive",
  "operation.errorAction.finishDownloadedPartFile": "finish downloaded part file",
  "operation.errorAction.finalizeSftpPartFile": "finalize SFTP part file",
  "operation.errorAction.flushTerminal": "flush terminal",
  "operation.errorAction.gitStatusTask": "Git status task",
  "operation.errorAction.launchTextEditor": "launch text editor",
  "operation.errorAction.move": "move",
  "operation.errorAction.moveToTrash": "move to Trash",
  "operation.errorAction.openArchive": "open archive",
  "operation.errorAction.openArchiveSource": "open archive source",
  "operation.errorAction.openCopySource": "open copy source",
  "operation.errorAction.openSftpFile": "open SFTP file",
  "operation.errorAction.openUploadSource": "open upload source",
  "operation.errorAction.openPreferences": "open preferences",
  "operation.errorAction.openPty": "open PTY",
  "operation.errorAction.openPtyWriter": "open PTY writer",
  "operation.errorAction.openKnownHosts": "open SSH known_hosts store",
  "operation.errorAction.archiveImageReaderTask": "archive image reader task",
  "operation.errorAction.archiveTextViewerTask": "archive text viewer task",
  "operation.errorAction.imageReaderTask": "image reader task",
  "operation.errorAction.textViewerTask": "text viewer task",
  "operation.errorAction.addSshHostKey": "add SSH host key",
  "operation.errorAction.parseMode": "parse mode",
  "operation.errorAction.parseEnglishLanguagePreset": "parse English language preset",
  "operation.errorAction.parseExternalCommands": "parse external commands",
  "operation.errorAction.parseJapaneseLanguagePreset": "parse Japanese language preset",
  "operation.errorAction.parseLocationProfiles": "parse location profiles",
  "operation.errorAction.parseQuenyaLanguagePreset": "parse Quenya language preset",
  "operation.errorAction.parseSettings": "parse settings",
  "operation.errorAction.readArchiveSourceDirectory": "read archive source directory",
  "operation.errorAction.readArchiveSourceMetadata": "read archive source metadata",
  "operation.errorAction.readDirectory": "read directory",
  "operation.errorAction.readDirectoryEntry": "read directory entry",
  "operation.errorAction.readDirectoryForDetailedDiff": "read directory for detailed diff",
  "operation.errorAction.readDirectorySize": "read directory size",
  "operation.errorAction.readEmptyFileMetadata": "read empty file metadata",
  "operation.errorAction.readFileForMd5": "read file for MD5",
  "operation.errorAction.readMetadata": "read metadata",
  "operation.errorAction.readMetadataForDetailedDiff": "read metadata for detailed diff",
  "operation.errorAction.readMetadataForDirectorySize": "read metadata for directory size",
  "operation.errorAction.readPermissions": "read permissions",
  "operation.errorAction.readArchive": "read archive",
  "operation.errorAction.readArchiveEntries": "read archive entries",
  "operation.errorAction.readArchiveEntry": "read archive entry",
  "operation.errorAction.readArchiveEntryBytes": "read archive entry bytes",
  "operation.errorAction.readArchiveEntryPath": "read archive entry path",
  "operation.errorAction.readSftpDirectory": "read SFTP directory",
  "operation.errorAction.readSftpMetadata": "read SFTP metadata",
  "operation.errorAction.readCopyStream": "read copy stream",
  "operation.errorAction.renameSftpEntry": "rename SFTP entry",
  "operation.errorAction.resolveSftpHost": "resolve SFTP host",
  "operation.errorAction.removeEmptyDirectory": "remove empty directory",
  "operation.errorAction.removeEmptySftpDirectory": "remove empty SFTP directory",
  "operation.errorAction.removeEmptySftpFile": "remove empty SFTP file",
  "operation.errorAction.removeEmptyFile": "remove empty file",
  "operation.errorAction.removeSftpDirectory": "remove SFTP directory",
  "operation.errorAction.resolveArchiveSource": "resolve archive source",
  "operation.errorAction.resolveArchiveDestinationParent": "resolve archive destination parent",
  "operation.errorAction.resolveDestinationParent": "resolve destination parent",
  "operation.errorAction.resolveSource": "resolve source",
  "operation.errorAction.resizeTerminal": "resize terminal",
  "operation.errorAction.runGitRevParse": "run git rev-parse",
  "operation.errorAction.runGitStatus": "run git status",
  "operation.errorAction.serializeExternalCommands": "serialize external commands",
  "operation.errorAction.serializeLocationProfiles": "serialize location profiles",
  "operation.errorAction.serializeSettings": "serialize settings",
  "operation.errorAction.setSftpReadTimeout": "set SFTP read timeout",
  "operation.errorAction.setSftpWriteTimeout": "set SFTP write timeout",
  "operation.errorAction.sftpConnectionTask": "SFTP connection task",
  "operation.errorAction.sftpDirectoryListingTask": "SFTP directory listing task",
  "operation.errorAction.searchTask": "search task",
  "operation.errorAction.sshHandshake": "SSH handshake",
  "operation.errorAction.spawnShell": "spawn shell",
  "operation.errorAction.unpackTarEntry": "unpack tar entry",
  "operation.errorAction.writeTerminal": "write terminal",
  "operation.errorAction.writeArchiveSource": "write archive source",
  "operation.errorAction.writeExtractedFile": "write extracted file",
  "operation.errorAction.writeCopyStream": "write copy stream",
  "operation.errorAction.writeSftpFile": "write SFTP file",
  "operation.field.directoryName": "directory name",
  "operation.field.fileName": "file name",
  "operation.field.archiveName": "archive name",
  "operation.field.mode": "mode",
  "operation.field.attributes": "attributes",
  "operation.field.newName": "new name",
  "operation.field.readonly": "readonly",
  "operation.field.hidden": "hidden",
  "operation.placeholder.mode": "xxx",
  "operation.placeholder.windowsAttributes": "readonly=keep hidden=keep",
  "operation.path.noSource": "(no source path)",
  "operation.path.noDestination": "(no destination)",
  "operation.path.emptyDirectory": "the empty directory",
  "operation.path.emptyFile": "the empty file",
  "operation.path.focusedItem": "the focused item",
  "operation.label.copy": "Copy to other pane",
  "operation.label.move": "Move to other pane",
  "operation.label.rename": "Rename focused entry",
  "operation.label.chmod": "Change permissions",
  "operation.label.windowsAttributes": "Change Windows attributes",
  "operation.label.trash": "Move selected entries to Trash",
  "operation.label.delete": "Delete selected entries permanently",
  "operation.label.mkdir": "Create directory",
  "operation.label.createFile": "Create file",
  "operation.label.removeEmptyDirectory": "Undo create directory",
  "operation.label.removeEmptyFile": "Undo create file",
  "operation.label.refresh": "Refresh active pane",
  "operation.label.extractArchive": "Extract archives to other pane",
  "operation.label.createArchive": "Create archive",
  "operation.planned.mkdir": "Create a new directory under {source}.",
  "operation.planned.createFile": "Create a new empty file under {source}.",
  "operation.planned.removeEmptyDirectory": "Remove empty directory {path}.",
  "operation.planned.removeEmptyFile": "Remove empty file {path}.",
  "operation.planned.refresh": "Reload directory listing for {source}.",
  "operation.planned.noTargets": "No target entries were resolved.",
  "operation.planned.copy": "Copy {path} to {destination}.",
  "operation.planned.move": "Move {path} to {destination}.",
  "operation.planned.extractArchive": "Extract {path} under {destination}.",
  "operation.planned.createArchive": "Create archive under {destination} from {count} item(s).",
  "operation.planned.rename": "Rename {path}.",
  "operation.planned.chmod": "Change permissions for {path}.",
  "operation.planned.windowsAttributes": "Change Windows attributes for {path}.",
  "operation.planned.trash": "Move {path} to Trash.",
  "operation.planned.delete": "Delete {path} permanently.",
  "operation.confirm.mkdir": "Create a new directory under {source}?",
  "operation.confirm.createFile": "Create a new empty file under {source}?",
  "operation.confirm.removeEmptyDirectory": "Undo directory creation by removing {path}?",
  "operation.confirm.removeEmptyFile": "Undo file creation by removing {path}?",
  "operation.confirm.refresh": "Refresh is safe and does not mutate the file system.",
  "operation.confirm.noTargets": "No targets are available; this job cannot execute.",
  "operation.confirm.copy": "Copy {count} item(s) to {destination}?",
  "operation.confirm.move": "Move {count} item(s) to {destination}?",
  "operation.confirm.extractArchive": "Extract {count} archive(s) to {destination}?",
  "operation.confirm.createArchive": "Create archive from {count} item(s) under {destination}?",
  "operation.confirm.rename": "Rename {path}?",
  "operation.confirm.chmod": "Change permissions for {count} item(s)?",
  "operation.confirm.windowsAttributes": "Change Windows attributes for {count} item(s)?",
  "operation.confirm.trash": "Move {count} item(s) to Trash?",
  "operation.confirm.delete": "Permanently delete {count} item(s)? This bypasses Trash and cannot be undone from Windy.",
  "operation.conflict.exists": "{name} already exists in {destination}.",
  "operation.conflict.currentName": "{name} is the current name.",
  "operation.blocking.archiveExtension": "Archive name must end with .zip, .tar, .tar.gz, or .tgz.",
  "operation.blocking.selfReference": "Cannot {kind} {path} into itself or one of its descendants: {destination}.",
  "operation.conflictSkipped": "\n\n{count} conflict(s) will be skipped.",
  "operation.summary.mkdir": "Creates one new directory.",
  "operation.summary.createFile": "Creates one new empty file.",
  "operation.summary.createArchive": "Creates one archive from {count} target(s).",
  "operation.summary.removeEmptyDirectory": "Removes one empty directory.",
  "operation.summary.removeEmptyFile": "Removes one empty file.",
  "operation.summary.refresh": "Refreshes the active pane listing.",
  "operation.summary.noTargets": "No target entries resolved.",
  "operation.summary.targets": "{count} target(s) resolved.",
  "undo.label.createDirectory": "Undo create directory",
  "undo.label.createFile": "Undo create file",
  "undo.label.rename": "Undo rename",
  "undo.label.redoRename": "Redo rename",
  "undo.label.renameStatus": "Undo rename {from} -> {to}",
  "undo.label.redoRenameStatus": "Redo rename {from} -> {to}",
  "undo.label.createdEntryStatus": "{label}: {name}",
  "undo.label.redoCreateDirectoryStatus": "Redo create directory: {name}",
  "undo.label.redoCreateFileStatus": "Redo create file: {name}",
  "undo.label.redoCreateDirectory": "Redo create directory",
  "undo.label.redoCreateFile": "Redo create file",
  "undo.planned.rename": "Rename {path} back to {name}.",
  "undo.confirm.rename": "Undo rename and restore {name}?",
  "undo.planned.removeEmptyDirectory": "Remove empty directory {path}.",
  "undo.planned.removeEmptyFile": "Remove empty file {path}.",
  "undo.confirm.removeEmptyDirectory": "Remove empty directory {path}?",
  "undo.confirm.removeEmptyFile": "Remove empty file {path}?",
  "undo.safety.sourceMoved": "The source pane is now at {current}, but this Undo was recorded for {recorded}.",
  "undo.safety.missingRestoreName": "Undo rename is missing the restore name.",
  "undo.safety.notVisible": "{path} is not visible in the current listing.",
  "undo.safety.sizeChanged": "{name} size changed after the original operation.",
  "undo.safety.modifiedChanged": "{name} modified time changed after the original operation.",
  "undo.safety.restoreExists": "{name} already exists; Undo rename may conflict.",
  "undo.safety.missingDirectoryTarget": "Undo directory removal target is missing.",
  "undo.safety.notDirectory": "{path} is no longer a directory.",
  "undo.safety.missingFileTarget": "Undo file removal target is missing.",
  "undo.safety.notFile": "{path} is no longer a file.",
  "undo.safety.notEmptyFile": "{path} is no longer empty; Undo will not remove it.",
  "location.title": "Location Manager",
  "location.sftpProfile": "SFTP Profile",
  "location.newSftpConnection": "New SFTP Connection",
  "location.kind.source": "source",
  "location.kind.saved": "saved",
  "location.kind.temporary": "temporary",
  "location.managerMessage": "Choose a location source for the active pane.",
  "location.sftpMessage": "Test an SFTP connection or save profile changes. Passwords are not saved.",
  "location.loading": "Loading...",
  "location.chooseEnter": "Choose: Enter",
  "location.connecting": "Connecting...",
  "location.trustHostKeyEnter": "Trust host key: Enter",
  "location.connectEnter": "Connect: Enter",
  "location.deleteSftpProfileConfirm": "Delete SFTP profile \"{name}\"? Press D or Enter to confirm, Esc to cancel.",
  "location.deleteLocalFavoriteConfirm": "Delete local favorite \"{name}\"? Press D or Enter to confirm, Esc to cancel.",
  "location.deleteSearchProfileConfirm": "Delete search profile \"{name}\"? Press D or Enter to confirm, Esc to cancel.",
  "location.sources": "Location sources",
  "location.field.name": "name",
  "location.field.host": "host",
  "location.field.port": "port",
  "location.field.user": "user",
  "location.field.auth": "auth",
  "location.field.password": "password",
  "location.field.keyPath": "key path",
  "location.field.passphrase": "passphrase",
  "location.field.remotePath": "remote path",
  "location.field.save": "save",
  "location.auth.password": "password",
  "location.auth.privateKey": "private key",
  "location.storeProfileWithoutPassword": "store this profile without password",
  "location.connectedAs": "{name} connected as {connectionId}",
  "location.unknownHostKey": "unknown host key",
  "location.addCurrentA": "Add current: A",
  "location.deleteSavedD": "Delete saved: D",
  "location.disconnectSessionQ": "Disconnect session: Q",
  "location.saveProfileCtrlS": "Save profile: ctrl+s",
  "search.title": "Search",
  "externalCommand.title": "External Commands",
  "externalCommand.badge": "phase 7-c",
  "externalCommand.message": "Choose a registered command to run with the active local selection.",
  "externalCommand.loading": "Loading...",
  "externalCommand.readingConfig": "Reading commands.json",
  "externalCommand.noCommands": "No commands",
  "externalCommand.noRunnableEntries": "commands.json did not contain runnable entries",
  "externalCommand.runEnter": "Run: Enter",
  "externalCommand.localSelectionOnly": "External commands are available for local selected paths only.",
  "search.dialogTitle": "Search Source",
  "search.badge.local": "local",
  "search.dialogMessage": "Create a virtual result source from local entries. Quick filter remains available inside the result.",
  "search.root": "root",
  "search.nameRegex": "name regex",
  "search.recursive": "recursive",
  "search.includeChildDirectories": "include child directories",
  "search.kind": "kind",
  "search.kind.all": "all",
  "search.kind.file": "file",
  "search.kind.directory": "directory",
  "search.kind.symlink": "symlink",
  "search.kind.other": "other",
  "search.minSize": "min size",
  "search.maxSize": "max size",
  "search.modifiedAfter": "modified after",
  "search.modifiedBefore": "modified before",
  "search.placeholder.date": "YYYYMMDD",
  "search.hidden": "hidden",
  "search.hidden.exclude": "exclude",
  "search.hidden.include": "include",
  "search.hidden.only": "only",
  "search.readonly": "readonly",
  "search.readonly.any": "any",
  "search.readonly.readonly": "readonly",
  "search.readonly.writable": "writable",
  "search.searching": "Searching...",
  "search.shortcutSearch": "Search: Enter",
  "largeSearch.title": "Large Search Result",
  "largeSearch.warning": "warning",
  "largeSearch.message": "Search found {count} item(s). Displaying a large virtual source can still feel heavy on this machine.",
  "largeSearch.displayEnter": "Display: Enter",
  "terminal.copyMode": "Terminal copy mode: move to select, Enter copies, Esc cancels.",
  "viewer.openFailed": "Viewer failed: {error}",
  "viewer.ariaLabel": "Internal {kind} viewer: {title}",
  "viewer.truncated": "truncated",
  "viewer.loading": "loading",
  "viewer.fit": "fit",
  "viewer.textHelp": "j/k, Space/b, g/G, /, n/N, q",
  "viewer.imageHelp": "+/- zoom, 0 fit, 1 actual, h/j/k/l pan, q",
  "viewer.searchFound": "Found: {query}",
  "viewer.searchNotFound": "Pattern not found: {query}",
  "viewer.searchEmpty": "Empty search.",
  "properties.title": "Properties",
  "properties.name": "Name",
  "properties.path": "Path",
  "properties.source": "Source",
  "properties.kind": "Kind",
  "properties.size": "Size",
  "properties.modified": "Modified",
  "properties.hidden": "Hidden",
  "properties.readonly": "Readonly",
  "properties.mode": "Mode",
  "properties.items": "Items",
  "properties.totalSize": "Total size",
  "properties.kinds": "Kinds",
  "properties.selectedItems": "Selected items",
  "properties.unknown": "unknown",
  "properties.directoryMarker": "<DIR>",
  "properties.unknownCount": "{count} unknown",
  "properties.kind.file": "file",
  "properties.kind.directory": "directory",
  "properties.kind.symlink": "symlink",
  "properties.kind.other": "other",
  "properties.sourceKind.local": "local",
  "properties.sourceKind.archive": "archive",
  "properties.sourceKind.sftp": "sftp",
  "properties.sourceKind.search": "search",
  "properties.sourceKind.diff": "diff",
  "properties.sourceKind.operationResult": "operation result",
  "properties.sourceKind.gitStatus": "git status",
  "diff.title": "Pane Diff",
  "diff.detailedTitle": "Detailed Pane Diff",
  "diff.summary": "{changed} changed / {identical} identical",
  "diff.left": "left",
  "diff.right": "right",
  "diff.leftOnly": "left only",
  "diff.rightOnly": "right only",
  "diff.kind": "kind",
  "diff.size": "size",
  "diff.modified": "modified",
  "diff.md5": "md5",
  "diff.readError": "read error",
  "diff.recursive": "recursive",
  "diff.entries": "Diff entries",
  "diff.noDifferences": "No differences",
  "diff.scrollShortcut": "Scroll: j/k PgUp/PgDn",
  "diff.status.leftOnly": "left only",
  "diff.status.rightOnly": "right only",
  "diff.status.kindDifferent": "kind different",
  "diff.status.sizeDifferent": "size different",
  "diff.status.modifiedDifferent": "modified different",
  "diff.status.hashDifferent": "hash different",
  "diff.status.readError": "read error",
  "diff.status.identical": "identical",
  "settings.loadFailed": "Settings load failed: {error}",
  "settings.appearanceLoadFailed": "Appearance settings load failed: {error}",
  "settings.keybindLoadFailed": "Keybind settings load failed: {error}",
  "shell.cmdUnsafePath": "cmd.exe cannot safely quote this path because it contains % or !: {path}",
  "shell.unknownShell": "The configured terminal shell has no safe path quoting rule.",
  "preferences.title": "Preferences",
  "preferences.subtitle": "Windy settings",
  "preferences.closeLabel": "Close preferences",
  "preferences.sectionsLabel": "Preference sections",
  "preferences.footerHint": "Esc closes preferences",
  "preferences.general": "General",
  "preferences.keybindings": "Keybindings",
  "preferences.appearance": "Appearance",
  "preferences.language": "Language",
  "preferences.reset": "Reset",
  "preferences.useTrash": "Use Trash for local delete",
  "preferences.editorCommand": "Default text editor command",
  "preferences.editorCommandPlaceholder": "code, vim, notepad.exe",
  "preferences.editorArgs": "Editor arguments, one per line",
  "preferences.openConfigDirectory": "Open Config Directory",
  "preferences.lockedBindings": "Locked Bindings",
  "preferences.keybindingUnsupportedSequence": "{command} uses unsupported key sequence '{binding}'. Use one or two keys.",
  "preferences.keybindingDuplicate": "Key '{binding}' is assigned to both {first} and {second}.",
  "preferences.keybindingPrefixConflict": "Key '{binding}' conflicts with the first key of {second} ({first}).",
  "preferences.uiFont": "UI font",
  "preferences.terminalFont": "Terminal font",
  "preferences.uiSize": "UI size",
  "preferences.terminalSize": "Terminal size",
  "preferences.viewerSize": "Viewer size",
  "preferences.fileRowHeight": "File row height",
  "preferences.colors": "Colors",
  "preferences.colorSettingsLabel": "Color settings",
  "preferences.interfaceColors": "Interface",
  "preferences.extensionColors": "Extensions",
  "preferences.colorPicker": "Color picker",
  "preferences.hexValue": "Hex value",
  "preferences.presetColorsLabel": "Preset colors",
  "preferences.setColor": "Set {color}",
  "preferences.removeExtensionColor": "Remove Extension Color",
  "preferences.selectColorItem": "Select a color item from the list.",
  "preferences.addExtensionColor": "Add Extension Color",
  "preferences.extension": "Extension",
  "preferences.extensionPlaceholder": "md",
  "preferences.color": "Color",
  "preferences.addOrUpdate": "Add or Update",
  "preferences.languageFile": "Language File",
  "preferences.preset": "Preset",
  "preferences.languagePreset.en": "English",
  "preferences.languagePreset.ja": "Japanese",
  "preferences.languagePreset.qya-Latn": "Quenya Latin",
  "preferences.currentLocale": "Current locale: {locale}",
  "preferences.languageCoverageNote": "Language files currently cover extracted message strings only.",
  "preferences.resetGeneral": "Reset General",
  "preferences.resetKeybindings": "Reset Keybindings",
  "preferences.resetAppearance": "Reset Appearance",
  "preferences.resetLanguage": "Reset Language",
  "preferences.resetNote": "Reset backs up current config files, then writes defaults for the selected area.",
  "preferences.safeMode": "Safe Mode",
  "preferences.safeModeNote": "Safe Mode backs up current config files and reloads defaults for General, Appearance, Keybindings, and Language.",
  "preferences.enterSafeMode": "Enter Safe Mode",
  "preferences.resetSettingsTitle": "Reset Settings",
  "preferences.resetConfirm": "Back up current config files and reset this setting group to defaults?",
  "preferences.safeModeConfirm": "Back up current config files and reload default settings now?",
  "preferences.statusOpened": "Preferences opened.",
  "preferences.statusLoadFailed": "Preferences load failed: {error}",
  "preferences.statusGeneralSaved": "General settings saved.",
  "preferences.statusGeneralSaveFailed": "General settings save failed: {error}",
  "preferences.statusAppearanceSaved": "Appearance settings saved.",
  "preferences.statusAppearanceSaveFailed": "Appearance settings save failed: {error}",
  "preferences.statusKeybindingsSaved": "Keybinding settings saved.",
  "preferences.statusKeybindingsSaveFailed": "Keybinding settings save failed: {error}",
  "preferences.statusLanguageApplied": "Language file applied: {locale}",
  "preferences.statusLanguageApplyFailed": "Language file apply failed: {error}",
  "preferences.statusConfigDirectoryOpened": "Config directory opened.",
  "preferences.statusConfigDirectoryFailed": "Open config directory failed: {error}",
  "preferences.statusReset": "Settings reset. Previous config files were backed up.",
  "preferences.statusResetFailed": "Settings reset failed: {error}",
  "preferences.statusSafeMode": "{message} Backups: {count}",
  "preferences.statusSafeModeFailed": "Safe Mode failed: {error}",
  "preferences.statusSafeModeStatusFailed": "Safe Mode status failed: {error}",
  "preferences.safeModeLoadedDefaults": "Safe Mode loaded default settings after backing up current config files.",
  "keyHelp.title": "Key Help",
  "keyHelp.currentBindings": "Current bindings",
  "keyHelp.closeHint": "? / Esc closes",
  "keyHelp.fixed": "fixed",
  "keyHelp.group.pane": "Pane",
  "keyHelp.group.entry": "Entry",
  "keyHelp.group.file": "File",
  "keyHelp.group.view": "View",
  "keyHelp.group.filter": "Filter",
  "keyHelp.group.diff": "Diff",
  "keyHelp.group.git": "Git",
  "keyHelp.group.clipboard": "Clipboard",
  "keyHelp.group.terminal": "Terminal",
  "keyHelp.group.location": "Location",
  "keyHelp.group.search": "Search",
  "keyHelp.group.external": "Command",
  "keyHelp.group.dialog": "Dialog",
  "keyHelp.group.help": "Help",
  "keyHelp.group.app": "App",
  "keyHelp.group.archive": "Archive",
  "keyHelp.group.selection": "Selection",
  "keyHelp.group.cursor": "Cursor",
  "keyHelp.command.pane.moveUp": "Move cursor up",
  "keyHelp.command.pane.moveDown": "Move cursor down",
  "keyHelp.command.pane.leftOrParent": "Left pane: parent / Right pane: focus left",
  "keyHelp.command.pane.rightOrParent": "Left pane: focus right / Right pane: parent",
  "keyHelp.command.pane.moveUpAlternative": "Move cursor up",
  "keyHelp.command.pane.moveDownAlternative": "Move cursor down",
  "keyHelp.command.pane.leftAlternative": "Left / parent alternative",
  "keyHelp.command.pane.rightAlternative": "Right / parent alternative",
  "keyHelp.command.pane.focusTerminal": "Focus terminal",
  "keyHelp.command.pane.goRoot": "Go to filesystem root",
  "keyHelp.command.pane.goHome": "Go to home directory",
  "keyHelp.command.pane.openOtherPathHere": "Open other pane path here",
  "keyHelp.command.pane.openCurrentPathInOther": "Open current path in other pane",
  "keyHelp.command.pane.focusNextByTab": "Focus next pane",
  "keyHelp.command.pane.focusPreviousByTab": "Focus previous pane",
  "keyHelp.command.terminal.focusPreviousPane": "Return from terminal",
  "keyHelp.command.terminal.toggleVisible": "Show/hide terminal",
  "keyHelp.command.terminal.toggleFullscreen": "Toggle terminal fullscreen",
  "keyHelp.command.terminal.copyMode": "Terminal copy mode",
  "keyHelp.command.terminal.insertActiveSelection": "Insert selected file path(s)",
  "keyHelp.command.terminal.scrollPageUp": "Scroll terminal one page up",
  "keyHelp.command.terminal.scrollPageDown": "Scroll terminal one page down",
  "keyHelp.command.terminal.scrollLineUp": "Scroll terminal one line up",
  "keyHelp.command.terminal.scrollLineDown": "Scroll terminal one line down",
  "keyHelp.command.terminal.break": "Send break to terminal",
  "keyHelp.command.location.openManager": "Open Location Manager",
  "keyHelp.command.search.openDialog": "Open search",
  "keyHelp.command.filter.startInline": "Start quick filter",
  "keyHelp.command.help.toggle": "Show key help",
  "keyHelp.command.app.refresh": "Refresh active pane",
  "keyHelp.command.app.undo": "Undo last supported operation",
  "keyHelp.command.app.redo": "Redo last undone operation",
  "keyHelp.command.selection.selectAll": "Select all visible entries",
  "keyHelp.command.selection.toggleFocused": "Toggle focused selection",
  "keyHelp.command.selection.extendUp": "Extend selection up",
  "keyHelp.command.selection.extendDown": "Extend selection down",
  "keyHelp.command.file.copy": "Copy to other pane",
  "keyHelp.command.file.move": "Move to other pane",
  "keyHelp.command.file.edit": "Edit focused file",
  "keyHelp.command.file.rename": "Rename focused entry",
  "keyHelp.command.file.delete": "Delete / move to Trash",
  "keyHelp.command.file.deletePermanently": "Delete permanently",
  "keyHelp.command.file.mkdir": "Create directory",
  "keyHelp.command.file.createFile": "Create empty file",
  "keyHelp.command.file.properties": "Show properties",
  "keyHelp.command.file.chmod": "Change permissions/attributes",
  "keyHelp.command.archive.unpack": "Unpack archive",
  "keyHelp.command.archive.create": "Create archive",
  "keyHelp.command.view.cycleSort": "Cycle sort mode",
  "keyHelp.command.view.toggleHidden": "Show/hide hidden files",
  "keyHelp.command.diff.openPaneDiff": "Compare left/right panes",
  "keyHelp.command.diff.openDetailedPaneDiff": "Compare local panes recursively with MD5",
  "keyHelp.command.git.openStatus": "Show Git changed files",
  "keyHelp.command.externalCommand.open": "Open external command list",
  "keyHelp.command.clipboard.copyPaths": "Copy selected path(s)",
  "keyHelp.command.clipboard.copyCurrentDirectory": "Copy current directory",
  "keyHelp.command.clipboard.copyNames": "Copy selected name(s)",
  "keyHelp.command.dialog.confirm": "Confirm dialog",
  "keyHelp.command.dialog.cancel": "Cancel dialog",
  "keyHelp.command.entry.open": "Open directory / viewer",
  "keyHelp.command.entry.openDefaultApp": "Open with OS default app",
  "keyHelp.command.entry.goParent": "Go to parent directory",
  "keyHelp.command.cursor.goFirst": "Go to first entry",
  "keyHelp.command.cursor.goLast": "Go to last entry",
  "keyHelp.command.cursor.pageUp": "Move cursor one page up",
  "keyHelp.command.cursor.pageDown": "Move cursor one page down",
  "menu.file": "File",
  "menu.edit": "Edit",
  "menu.view": "View",
  "menu.window": "Window",
  "menu.help": "Help",
  "menu.settings": "Settings",
  "menu.preferences": "Preferences...",
  "menu.languageFile": "Language File",
  "menu.language.english": "English",
  "menu.language.japanese": "Japanese",
  "menu.language.quenyaLatin": "Quenya Latin",
};

export type Translate = (id: string, values?: Record<string, string | number>) => string;

export function translateMessage(
  settings: LanguageSettings | null | undefined,
  id: string,
  values: Record<string, string | number> = {},
): string {
  const template = settings?.messages?.[id] ?? defaultMessages[id] ?? id;
  return template.replace(/\{([a-zA-Z0-9_.-]+)\}/g, (match, key) => (
    values[key] === undefined ? match : String(values[key])
  ));
}

export function createTranslator(settings: LanguageSettings | null | undefined): Translate {
  return (id, values) => translateMessage(settings, id, values);
}
