import type { FileOperationResult, FileOperationResultItem } from "./types";
import { translateMessage, type Translate } from "./localization";

const fallbackTranslate: Translate = (id, values) => translateMessage(undefined, id, values);

const exactOperationMessages: Record<string, string> = {
  "This SFTP file operation is not implemented yet.": "operation.resultMessage.sftpOperationUnsupported",
  "Refresh completed.": "operation.resultMessage.refreshCompleted",
  "SFTP to SFTP copy is not implemented yet.": "operation.resultMessage.sftpToSftpCopyUnsupported",
  "SFTP copy requires a local/SFTP source and destination.": "operation.resultMessage.sftpCopyRequiresMixedSources",
  "Target is not an SFTP path.": "operation.resultMessage.targetNotSftpPath",
  "Mixed SFTP connections in one copy job are not supported.": "operation.resultMessage.mixedSftpCopyUnsupported",
  "SFTP target has no file name.": "operation.resultMessage.sftpTargetMissingFileName",
  "Local target has no file name.": "operation.resultMessage.localTargetMissingFileName",
  "SFTP delete requires SFTP targets.": "operation.resultMessage.sftpDeleteRequiresTargets",
  "Mixed SFTP connections in one delete job are not supported.": "operation.resultMessage.mixedSftpDeleteUnsupported",
  "Deleted permanently from SFTP.": "operation.resultMessage.deletedFromSftp",
  "No target was resolved.": "operation.resultMessage.noTargetResolved",
  "SFTP target has no parent directory.": "operation.resultMessage.sftpTargetMissingParent",
  "Requested name is the current name.": "operation.resultMessage.requestedNameIsCurrent",
  "SFTP mkdir requires an SFTP destination.": "operation.resultMessage.sftpMkdirRequiresDestination",
  "Destination already exists.": "operation.resultMessage.destinationExists",
  "Directory created on SFTP.": "operation.resultMessage.sftpDirectoryCreated",
  "SFTP file creation requires an SFTP destination.": "operation.resultMessage.sftpCreateFileRequiresDestination",
  "File created on SFTP.": "operation.resultMessage.sftpFileCreated",
  "SFTP chmod requires SFTP targets.": "operation.resultMessage.sftpChmodRequiresTargets",
  "Mixed SFTP connections in one chmod job are not supported.": "operation.resultMessage.mixedSftpChmodUnsupported",
  "Removed empty SFTP directory.": "operation.resultMessage.sftpEmptyDirectoryRemoved",
  "Undo can remove only an empty SFTP file.": "operation.resultMessage.undoRequiresEmptySftpFile",
  "Removed empty SFTP file.": "operation.resultMessage.sftpEmptyFileRemoved",
  "Target has no parent directory.": "operation.resultMessage.targetMissingParent",
  "Changed Windows attributes.": "operation.resultMessage.windowsAttributesChanged",
  "Deleted permanently.": "operation.resultMessage.deletedPermanently",
  "Moved to Trash.": "operation.resultMessage.movedToTrash",
  "Directory created.": "operation.resultMessage.directoryCreated",
  "File created.": "operation.resultMessage.fileCreated",
  "Removed empty directory.": "operation.resultMessage.emptyDirectoryRemoved",
  "Undo can remove only an empty file.": "operation.resultMessage.undoRequiresEmptyFile",
  "Removed empty file.": "operation.resultMessage.emptyFileRemoved",
  "No archive sources were resolved.": "operation.resultMessage.noArchiveSources",
  "Archive name must end with .zip, .tar, .tar.gz, or .tgz.": "operation.resultMessage.archiveExtensionRequired",
  "Cannot create an archive inside a selected source directory.": "operation.resultMessage.archiveInsideSource",
  "Archive links are not allowed for extraction.": "operation.resultMessage.archiveLinksNotAllowed",
  "Archive special entries are not allowed for extraction.": "operation.resultMessage.archiveSpecialEntriesNotAllowed",
  "Archive entry path is empty.": "operation.resultMessage.archiveEntryPathEmpty",
  "Archive creation canceled.": "operation.resultMessage.archiveCreationCanceled",
  "Archive extraction canceled.": "operation.resultMessage.archiveExtractionCanceled",
  "Archive extraction exceeded the 100,000 entry limit.": "operation.resultMessage.archiveExtractionEntryLimit",
  "Archive extraction exceeded the 64 GiB expanded size limit.": "operation.resultMessage.archiveExtractionSizeLimit",
  "Archive listing exceeded the 100,000 entry limit.": "operation.resultMessage.archiveListingLimit",
  "Directory listing exceeded the 100,000 entry limit.": "operation.resultMessage.directoryListingLimit",
  "SFTP listing exceeded the 100,000 entry limit.": "operation.resultMessage.sftpListingLimit",
  "Detailed diff canceled.": "operation.resultMessage.detailedDiffCanceled",
  "Search min size must be less than or equal to max size": "operation.resultMessage.searchSizeRange",
  "Search modified-after must be less than or equal to modified-before": "operation.resultMessage.searchDateRange",
  "Unsupported search kind.": "operation.resultMessage.unsupportedSearchKind",
  "Unsupported hidden search mode.": "operation.resultMessage.unsupportedHiddenSearchMode",
  "Unsupported readonly search mode.": "operation.resultMessage.unsupportedReadonlySearchMode",
  "SFTP host is required.": "operation.resultMessage.sftpHostRequired",
  "SFTP port must be between 1 and 65535.": "operation.resultMessage.sftpPortRange",
  "SFTP username is required.": "operation.resultMessage.sftpUsernameRequired",
  "SFTP password is required.": "operation.resultMessage.sftpPasswordRequired",
  "SFTP private key path is required.": "operation.resultMessage.sftpPrivateKeyRequired",
  "Unsupported SFTP authentication kind.": "operation.resultMessage.unsupportedSftpAuth",
  "SFTP connection state is unavailable.": "operation.resultMessage.sftpConnectionStateUnavailable",
  "SSH server host key type is unknown.": "operation.resultMessage.sshHostKeyUnknown",
  "SSH server host key is unavailable.": "operation.resultMessage.sshHostKeyUnavailable",
  "Terminal is not running.": "operation.resultMessage.terminalNotRunning",
  "Terminal state lock poisoned.": "operation.resultMessage.terminalStateLockPoisoned",
  "Safe Mode state lock failed.": "operation.resultMessage.safeModeStateLockFailed",
  "Home directory could not be resolved.": "operation.resultMessage.homeDirectoryUnresolved",
  "Home directory could not be resolved for known_hosts.": "operation.resultMessage.homeDirectoryUnresolvedForKnownHosts",
  "Config directory could not be resolved.": "operation.resultMessage.configDirectoryUnresolved",
  "Uploading symlinks to SFTP is not implemented yet.": "operation.resultMessage.sftpUploadSymlinkUnsupported",
  "Path is empty.": "operation.resultMessage.pathEmpty",
  "Destination path is not set.": "operation.resultMessage.destinationPathNotSet",
  "Name is not set.": "operation.resultMessage.nameNotSet",
  "Mode is not set.": "operation.resultMessage.modeNotSet",
  "Windows attribute expression is not set.": "operation.resultMessage.windowsAttributeExpressionNotSet",
  "Mode must be an octal value like 644, 755, or 0755.": "operation.resultMessage.modeOctalRequired",
  "No Windows attribute changes were requested.": "operation.resultMessage.noWindowsAttributeChanges",
  "Attribute values must be on, off, or keep.": "operation.resultMessage.windowsAttributeValues",
  "Supported Windows attributes are readonly/r and hidden/h.": "operation.resultMessage.supportedWindowsAttributes",
  "Name must not contain path separators.": "operation.resultMessage.namePathSeparators",
  "Name must not contain NUL characters.": "operation.resultMessage.nameNul",
  "Name contains characters that are invalid on Windows.": "operation.resultMessage.nameInvalidWindows",
  "Name is reserved on Windows.": "operation.resultMessage.nameReservedWindows",
  "Name must not end with a space or period on Windows.": "operation.resultMessage.nameTrailingWindows",
  "Search profile name is required.": "operation.resultMessage.searchProfileNameRequired",
  "Local favorite name is required.": "operation.resultMessage.localFavoriteNameRequired",
  "SFTP profile name is required.": "operation.resultMessage.sftpProfileNameRequired",
  "SFTP profile id is required.": "operation.resultMessage.sftpProfileIdRequired",
  "Local favorite id is required.": "operation.resultMessage.localFavoriteIdRequired",
  "Search profile id is required.": "operation.resultMessage.searchProfileIdRequired",
  "External command id is required.": "operation.resultMessage.externalCommandIdRequired",
  "Text editor is not configured. Register it from Settings > Text Editor.": "operation.resultMessage.textEditorNotConfigured",
  "Archive entry has no file name.": "operation.resultMessage.archiveEntryMissingFileName",
};

const operationErrorActionIds: Record<string, string> = {
  "Add zip directory": "operation.errorAction.addZipDirectory",
  "Add zip file": "operation.errorAction.addZipFile",
  "add zip directory": "operation.errorAction.addZipDirectory",
  "add zip file": "operation.errorAction.addZipFile",
  "append tar directory": "operation.errorAction.appendTarDirectory",
  "append tar file": "operation.errorAction.appendTarFile",
  "change hidden attribute": "operation.errorAction.changeHiddenAttribute",
  "change permissions": "operation.errorAction.changePermissions",
  "change readonly attribute": "operation.errorAction.changeReadonlyAttribute",
  "Change SFTP mode": "operation.errorAction.changeSftpMode",
  "Clone PTY reader": "operation.errorAction.clonePtyReader",
  "Create SSH session": "operation.errorAction.createSshSession",
  "create archive": "operation.errorAction.createArchive",
  "create copy destination": "operation.errorAction.createCopyDestination",
  "create directory": "operation.errorAction.createDirectory",
  "create directory symlink": "operation.errorAction.createDirectorySymlink",
  "create download directory": "operation.errorAction.createDownloadDirectory",
  "create download parent directory": "operation.errorAction.createDownloadParentDirectory",
  "create downloaded file": "operation.errorAction.createDownloadedFile",
  "Create SFTP directory": "operation.errorAction.createSftpDirectory",
  "Create SFTP file": "operation.errorAction.createSftpFile",
  "create extracted directory": "operation.errorAction.createExtractedDirectory",
  "create extracted file": "operation.errorAction.createExtractedFile",
  "create extracted parent directory": "operation.errorAction.createExtractedParentDirectory",
  "create extraction directory": "operation.errorAction.createExtractionDirectory",
  "create file": "operation.errorAction.createFile",
  "create file symlink": "operation.errorAction.createFileSymlink",
  "create symlink": "operation.errorAction.createSymlink",
  delete: "operation.errorAction.delete",
  "Delete SFTP file": "operation.errorAction.deleteSftpFile",
  "Detailed diff task": "operation.errorAction.detailedDiffTask",
  "Directory listing task": "operation.errorAction.directoryListingTask",
  "Archive listing task": "operation.errorAction.archiveListingTask",
  "File operation task": "operation.errorAction.fileOperationTask",
  "finish archive": "operation.errorAction.finishArchive",
  "Finish gzip stream": "operation.errorAction.finishGzipStream",
  "Finish tar entries": "operation.errorAction.finishTarEntries",
  "Finish tar.gz archive": "operation.errorAction.finishTarGzArchive",
  "Finish zip archive": "operation.errorAction.finishZipArchive",
  "finish downloaded part file": "operation.errorAction.finishDownloadedPartFile",
  "Finalize SFTP part file": "operation.errorAction.finalizeSftpPartFile",
  "Flush terminal": "operation.errorAction.flushTerminal",
  "Git status task": "operation.errorAction.gitStatusTask",
  "Launch text editor": "operation.errorAction.launchTextEditor",
  move: "operation.errorAction.move",
  "Move to Trash": "operation.errorAction.moveToTrash",
  "open archive": "operation.errorAction.openArchive",
  "open archive source": "operation.errorAction.openArchiveSource",
  "open copy source": "operation.errorAction.openCopySource",
  "Open SFTP file": "operation.errorAction.openSftpFile",
  "open upload source": "operation.errorAction.openUploadSource",
  "Open preferences": "operation.errorAction.openPreferences",
  "Open PTY": "operation.errorAction.openPty",
  "Open PTY writer": "operation.errorAction.openPtyWriter",
  "Open SSH known_hosts store": "operation.errorAction.openKnownHosts",
  "Archive image reader task": "operation.errorAction.archiveImageReaderTask",
  "Archive text viewer task": "operation.errorAction.archiveTextViewerTask",
  "Image reader task": "operation.errorAction.imageReaderTask",
  "Text viewer task": "operation.errorAction.textViewerTask",
  "Add SSH host key": "operation.errorAction.addSshHostKey",
  "Parse mode": "operation.errorAction.parseMode",
  "Parse English language preset": "operation.errorAction.parseEnglishLanguagePreset",
  "Parse external commands": "operation.errorAction.parseExternalCommands",
  "Parse Japanese language preset": "operation.errorAction.parseJapaneseLanguagePreset",
  "Parse location profiles": "operation.errorAction.parseLocationProfiles",
  "Parse Quenya language preset": "operation.errorAction.parseQuenyaLanguagePreset",
  "Parse settings": "operation.errorAction.parseSettings",
  "read archive source directory": "operation.errorAction.readArchiveSourceDirectory",
  "read archive source metadata": "operation.errorAction.readArchiveSourceMetadata",
  "read directory": "operation.errorAction.readDirectory",
  "read directory entry": "operation.errorAction.readDirectoryEntry",
  "read directory for detailed diff": "operation.errorAction.readDirectoryForDetailedDiff",
  "read directory size": "operation.errorAction.readDirectorySize",
  "read empty file metadata": "operation.errorAction.readEmptyFileMetadata",
  "read file for md5": "operation.errorAction.readFileForMd5",
  "read metadata": "operation.errorAction.readMetadata",
  "read metadata for detailed diff": "operation.errorAction.readMetadataForDetailedDiff",
  "read metadata for directory size": "operation.errorAction.readMetadataForDirectorySize",
  "read permissions": "operation.errorAction.readPermissions",
  "Read archive": "operation.errorAction.readArchive",
  "Read archive entries": "operation.errorAction.readArchiveEntries",
  "Read archive entry": "operation.errorAction.readArchiveEntry",
  "Read archive entry bytes": "operation.errorAction.readArchiveEntryBytes",
  "Read archive entry path": "operation.errorAction.readArchiveEntryPath",
  "Read SFTP directory": "operation.errorAction.readSftpDirectory",
  "Read SFTP metadata": "operation.errorAction.readSftpMetadata",
  "Read copy stream": "operation.errorAction.readCopyStream",
  "Rename SFTP entry": "operation.errorAction.renameSftpEntry",
  "Resolve SFTP host": "operation.errorAction.resolveSftpHost",
  "remove empty directory": "operation.errorAction.removeEmptyDirectory",
  "Remove empty SFTP directory": "operation.errorAction.removeEmptySftpDirectory",
  "Remove empty SFTP file": "operation.errorAction.removeEmptySftpFile",
  "remove empty file": "operation.errorAction.removeEmptyFile",
  "Remove SFTP directory": "operation.errorAction.removeSftpDirectory",
  "resolve archive source": "operation.errorAction.resolveArchiveSource",
  "resolve archive destination parent": "operation.errorAction.resolveArchiveDestinationParent",
  "resolve destination parent": "operation.errorAction.resolveDestinationParent",
  "resolve source": "operation.errorAction.resolveSource",
  "Resize terminal": "operation.errorAction.resizeTerminal",
  "Run git rev-parse": "operation.errorAction.runGitRevParse",
  "Run git status": "operation.errorAction.runGitStatus",
  "Serialize external commands": "operation.errorAction.serializeExternalCommands",
  "Serialize location profiles": "operation.errorAction.serializeLocationProfiles",
  "Serialize settings": "operation.errorAction.serializeSettings",
  "Set SFTP read timeout": "operation.errorAction.setSftpReadTimeout",
  "Set SFTP write timeout": "operation.errorAction.setSftpWriteTimeout",
  "SFTP connection task": "operation.errorAction.sftpConnectionTask",
  "SFTP directory listing task": "operation.errorAction.sftpDirectoryListingTask",
  "Search task": "operation.errorAction.searchTask",
  "SSH handshake": "operation.errorAction.sshHandshake",
  "Spawn shell": "operation.errorAction.spawnShell",
  "unpack tar entry": "operation.errorAction.unpackTarEntry",
  "Write terminal": "operation.errorAction.writeTerminal",
  "write archive source": "operation.errorAction.writeArchiveSource",
  "write extracted file": "operation.errorAction.writeExtractedFile",
  "Write copy stream": "operation.errorAction.writeCopyStream",
  "Write SFTP file": "operation.errorAction.writeSftpFile",
};

function operationErrorActionLabel(action: string, t: Translate): string {
  const id = operationErrorActionIds[action];
  if (!id) return action;
  const translated = t(id);
  return translated === id ? action : translated;
}

function translateLegacyOperationMessage(message: string, t: Translate): string | null {
  const exactId = exactOperationMessages[message];
  if (exactId) {
    const translated = t(exactId);
    return translated === exactId ? null : translated;
  }

  const dynamicPatterns: Array<[RegExp, string, (match: RegExpMatchArray) => Record<string, string | number>]> = [
    [/^Copied to '(.+)'\.$/, "operation.resultMessage.copiedTo", (match) => ({ destination: match[1] })],
    [/^Moved to '(.+)'\.$/, "operation.resultMessage.movedTo", (match) => ({ destination: match[1] })],
    [/^Renamed to '(.+)'\.$/, "operation.resultMessage.renamedTo", (match) => ({ destination: match[1] })],
    [/^Downloaded to '(.+)'\.$/, "operation.resultMessage.downloadedTo", (match) => ({ destination: match[1] })],
    [/^Uploaded to '(.+)'\.$/, "operation.resultMessage.uploadedTo", (match) => ({ destination: match[1] })],
    [/^Extracted to '(.+)'\.$/, "operation.resultMessage.extractedTo", (match) => ({ destination: match[1] })],
    [/^Destination already exists: '(.+)'$/, "operation.resultMessage.destinationExistsAt", (match) => ({ destination: match[1] })],
    [/^Changed mode to ([0-7]+)\.$/, "operation.resultMessage.modeChanged", (match) => ({ mode: match[1] })],
    [/^Changed remote mode to ([0-7]+)\.$/, "operation.resultMessage.remoteModeChanged", (match) => ({ mode: match[1] })],
    [/^Archive created with (\d+) item\(s\)\.$/, "operation.resultMessage.archiveCreated", (match) => ({ count: Number(match[1]) })],
    [/^SFTP connection is busy or unavailable: (.+)$/, "operation.resultMessage.sftpConnectionBusy", (match) => ({ connectionId: match[1] })],
    [/^SFTP connection is not available: (.+)$/, "operation.resultMessage.sftpConnectionUnavailable", (match) => ({ connectionId: match[1] })],
    [/^Start SFTP subsystem failed: (.+)$/, "operation.resultMessage.sftpSubsystemFailed", (match) => ({ error: match[1] })],
    [/^Rename SFTP entry failed for '(.+)': (.+)$/, "operation.resultMessage.renameSftpEntryFailed", (match) => ({ path: match[1], error: match[2] })],
    [/^Change SFTP mode failed for '(.+)': (.+)$/, "operation.resultMessage.changeSftpModeFailed", (match) => ({ path: match[1], error: match[2] })],
    [/^Delete SFTP file failed for '(.+)': (.+)$/, "operation.resultMessage.deleteSftpFileFailed", (match) => ({ path: match[1], error: match[2] })],
    [/^Create SFTP directory failed: (.+)$/, "operation.resultMessage.createSftpDirectoryFailed", (match) => ({ error: match[1] })],
    [/^Create SFTP file failed: (.+)$/, "operation.resultMessage.createSftpFileFailed", (match) => ({ error: match[1] })],
    [/^Remove empty SFTP directory failed for '(.+)': (.+)$/, "operation.resultMessage.removeEmptySftpDirectoryFailed", (match) => ({ path: match[1], error: match[2] })],
    [/^Remove empty SFTP file failed for '(.+)': (.+)$/, "operation.resultMessage.removeEmptySftpFileFailed", (match) => ({ path: match[1], error: match[2] })],
    [/^Read SFTP metadata failed for '(.+)': (.+)$/, "operation.resultMessage.readSftpMetadataFailed", (match) => ({ path: match[1], error: match[2] })],
    [/^Read SFTP directory failed for '(.+)': (.+)$/, "operation.resultMessage.readSftpDirectoryFailed", (match) => ({ path: match[1], error: match[2] })],
    [/^Open SFTP file failed for '(.+)': (.+)$/, "operation.resultMessage.openSftpFileFailed", (match) => ({ path: match[1], error: match[2] })],
    [/^Finalize SFTP part file failed for '(.+)': (.+)$/, "operation.resultMessage.finalizeSftpPartFileFailed", (match) => ({ path: match[1], error: match[2] })],
    [/^Remove SFTP directory failed for '(.+)': (.+)$/, "operation.resultMessage.removeSftpDirectoryFailed", (match) => ({ path: match[1], error: match[2] })],
    [/^Move to Trash failed for '(.+)': (.+)$/, "operation.resultMessage.moveToTrashFailed", (match) => ({ path: match[1], error: match[2] })],
    [/^Read archive failed: (.+)$/, "operation.resultMessage.readArchiveFailed", (match) => ({ error: match[1] })],
    [/^Read archive entries failed: (.+)$/, "operation.resultMessage.readArchiveEntriesFailed", (match) => ({ error: match[1] })],
    [/^Read archive entry failed: (.+)$/, "operation.resultMessage.readArchiveEntryFailed", (match) => ({ error: match[1] })],
    [/^Read archive entry path failed: (.+)$/, "operation.resultMessage.readArchiveEntryPathFailed", (match) => ({ error: match[1] })],
    [/^Read archive entry bytes failed: (.+)$/, "operation.resultMessage.readArchiveEntryBytesFailed", (match) => ({ error: match[1] })],
    [/^Finish zip archive failed: (.+)$/, "operation.resultMessage.finishZipArchiveFailed", (match) => ({ error: match[1] })],
    [/^Finish tar\.gz archive failed: (.+)$/, "operation.resultMessage.finishTarGzArchiveFailed", (match) => ({ error: match[1] })],
    [/^Finish gzip stream failed: (.+)$/, "operation.resultMessage.finishGzipStreamFailed", (match) => ({ error: match[1] })],
    [/^Finish tar entries failed: (.+)$/, "operation.resultMessage.finishTarEntriesFailed", (match) => ({ error: match[1] })],
    [/^Open PTY failed: (.+)$/, "operation.resultMessage.openPtyFailed", (match) => ({ error: match[1] })],
    [/^Spawn shell failed: (.+)$/, "operation.resultMessage.spawnShellFailed", (match) => ({ error: match[1] })],
    [/^Write terminal failed: (.+)$/, "operation.resultMessage.writeTerminalFailed", (match) => ({ error: match[1] })],
    [/^Image reader task failed: (.+)$/, "operation.resultMessage.imageReaderTaskFailed", (match) => ({ error: match[1] })],
    [/^Text viewer task failed: (.+)$/, "operation.resultMessage.textViewerTaskFailed", (match) => ({ error: match[1] })],
    [/^No socket address resolved for (.+):(\d+)$/, "operation.resultMessage.noSocketAddress", (match) => ({ host: match[1], port: match[2] })],
    [/^Unsupported archive type: '(.+)'$/, "operation.resultMessage.unsupportedArchiveType", (match) => ({ path: match[1] })],
    [/^Not a tar archive: '(.+)'$/, "operation.resultMessage.notTarArchive", (match) => ({ path: match[1] })],
    [/^Destination has no file name: '(.+)'$/, "operation.resultMessage.destinationMissingFileName", (match) => ({ path: match[1] })],
    [/^Archive source has no file name: '(.+)'$/, "operation.resultMessage.archiveSourceMissingFileName", (match) => ({ path: match[1] })],
    [/^Archive destination has no parent: '(.+)'$/, "operation.resultMessage.archiveDestinationMissingParent", (match) => ({ path: match[1] })],
    [/^Archive destination parent cannot be resolved: '(.+)'$/, "operation.resultMessage.archiveDestinationParentUnresolved", (match) => ({ path: match[1] })],
    [/^Source has no file name: '(.+)'$/, "operation.resultMessage.sourceMissingFileName", (match) => ({ path: match[1] })],
    [/^Destination has no parent: '(.+)'$/, "operation.resultMessage.destinationMissingParentPath", (match) => ({ path: match[1] })],
    [/^Archive entry has an unsafe path: '(.+)'$/, "operation.resultMessage.archiveUnsafePath", (match) => ({ path: match[1] })],
    [/^Archive entry is a directory: (.+)$/, "operation.resultMessage.archiveEntryDirectory", (match) => ({ path: match[1] })],
    [/^Invalid name regex: (.+)$/, "operation.resultMessage.invalidNameRegex", (match) => ({ error: match[1] })],
    [/^SFTP profile was not found: (.+)$/, "operation.resultMessage.sftpProfileNotFound", (match) => ({ id: match[1] })],
    [/^Local favorite was not found: (.+)$/, "operation.resultMessage.localFavoriteNotFound", (match) => ({ id: match[1] })],
    [/^Search profile was not found: (.+)$/, "operation.resultMessage.searchProfileNotFound", (match) => ({ id: match[1] })],
    [/^Invalid archive entry path: (.+)$/, "operation.resultMessage.invalidArchiveEntryPath", (match) => ({ path: match[1] })],
    [/^Unsupported image extension: \.(.+)$/, "operation.resultMessage.unsupportedImageExtension", (match) => ({ extension: match[1] })],
    [/^Not a regular file: '(.+)'$/, "operation.resultMessage.notRegularFile", (match) => ({ path: match[1] })],
    [/^Unknown language preset: (.+)$/, "operation.resultMessage.unknownLanguagePreset", (match) => ({ locale: match[1] })],
    [/^Temporary archive already exists: '(.+)'$/, "operation.resultMessage.temporaryArchiveExists", (match) => ({ path: match[1] })],
    [/^SFTP part file already exists: '(.+)'$/, "operation.resultMessage.sftpPartFileExists", (match) => ({ path: match[1] })],
    [/^Extracted destination already exists: '(.+)'$/, "operation.resultMessage.extractedDestinationExists", (match) => ({ path: match[1] })],
    [/^Archive entry was not found: '(.+)::\/(.+)'$/, "operation.resultMessage.archiveEntryNotFound", (match) => ({ archive: match[1], path: match[2] })],
    [/^Text editor target must be a local file: (.+)$/, "operation.resultMessage.textEditorTargetMustBeFile", (match) => ({ path: match[1] })],
    [/^Path must resolve to a local absolute path: (.+)$/, "operation.resultMessage.pathMustResolveToAbsolute", (match) => ({ path: match[1] })],
    [/^Search root is not a directory: (.+)$/, "operation.resultMessage.searchRootNotDirectory", (match) => ({ path: match[1] })],
    [/^Local favorite path is not a directory: (.+)$/, "operation.resultMessage.localFavoritePathNotDirectory", (match) => ({ path: match[1] })],
    [/^Git root could not be resolved for (.+)\.$/, "operation.resultMessage.gitRootUnresolved", (match) => ({ path: match[1] })],
    [/^(git status|git rev-parse) failed\.$/, "operation.resultMessage.gitCommandFailed", (match) => ({ command: match[1] })],
    [/^(git status|git rev-parse) failed: (.+)$/, "operation.resultMessage.gitCommandFailedWithMessage", (match) => ({ command: match[1], error: match[2] })],
    [/^(.+) path does not exist: (.+)$/, "operation.resultMessage.diffRootMissing", (match) => ({ label: match[1], path: match[2] })],
    [/^(.+) path is not a directory: (.+)$/, "operation.resultMessage.diffRootNotDirectory", (match) => ({ label: match[1], path: match[2] })],
    [/^Terminal cwd is not a directory: '(.+)'$/, "operation.resultMessage.terminalCwdNotDirectory", (match) => ({ path: match[1] })],
    [/^External command name is required: (.+)$/, "operation.resultMessage.externalCommandNameRequired", (match) => ({ id: match[1] })],
    [/^External command template is required: (.+)$/, "operation.resultMessage.externalCommandTemplateRequired", (match) => ({ id: match[1] })],
    [/^External command argumentMode must be args, repeat, or join: (.+)$/, "operation.resultMessage.externalCommandArgumentMode", (match) => ({ id: match[1] })],
    [/^Safe Mode startup failed: (.+)$/, "operation.resultMessage.safeModeStartupFailed", (match) => ({ error: match[1] })],
    [/^(.+) private key path is required\.$/, "operation.resultMessage.sftpPrivateKeyPathRequiredFor", (match) => ({ label: match[1] })],
    [/^(.+) private key file does not exist: (.+)$/, "operation.resultMessage.sftpPrivateKeyFileMissing", (match) => ({ label: match[1], path: match[2] })],
    [/^(.+) private key authentication failed: (.+)$/, "operation.resultMessage.sftpPrivateKeyAuthFailed", (match) => ({ label: match[1], error: match[2] })],
    [/^(.+) password authentication failed: (.+)$/, "operation.resultMessage.sftpPasswordAuthFailed", (match) => ({ label: match[1], error: match[2] })],
    [/^(.+) authentication failed\.$/, "operation.resultMessage.sftpAuthFailed", (match) => ({ label: match[1] })],
    [/^SSH host key mismatch for (.+):(\d+)\. Check (.+) before connecting\.$/, "operation.resultMessage.sshHostKeyMismatch", (match) => ({ host: match[1], port: match[2], path: match[3] })],
    [/^SSH known_hosts check failed for (.+):(\d+) using (.+)\.$/, "operation.resultMessage.sshKnownHostsCheckFailed", (match) => ({ host: match[1], port: match[2], path: match[3] })],
    [/^Read SSH known_hosts failed \((.+)\): (.+)$/, "operation.resultMessage.sshKnownHostsReadFailed", (match) => ({ path: match[1], error: match[2] })],
    [/^Create SSH known_hosts directory failed \((.+)\): (.+)$/, "operation.resultMessage.sshKnownHostsDirectoryFailed", (match) => ({ path: match[1], error: match[2] })],
    [/^Write SSH known_hosts failed \((.+)\): (.+)$/, "operation.resultMessage.sshKnownHostsWriteFailed", (match) => ({ path: match[1], error: match[2] })],
    [/^Connect to SFTP host failed for (.+):(\d+)\. Tried: (.+)$/, "operation.resultMessage.sftpConnectHostFailed", (match) => ({ host: match[1], port: match[2], tried: match[3] })],
    [/^Create SSH session failed: (.+)$/, "operation.resultMessage.createSshSessionFailed", (match) => ({ error: match[1] })],
    [/^Resolve SFTP host failed: (.+)$/, "operation.resultMessage.resolveSftpHostFailed", (match) => ({ error: match[1] })],
    [/^Open SSH known_hosts store failed: (.+)$/, "operation.resultMessage.openSshKnownHostsStoreFailed", (match) => ({ error: match[1] })],
    [/^Read SFTP directory failed: (.+)$/, "operation.resultMessage.readSftpDirectoryPlainFailed", (match) => ({ error: match[1] })],
    [/^Parse location profiles failed: (.+)$/, "operation.resultMessage.parseLocationProfilesFailed", (match) => ({ error: match[1] })],
    [/^Serialize location profiles failed: (.+)$/, "operation.resultMessage.serializeLocationProfilesFailed", (match) => ({ error: match[1] })],
    [/^Parse external commands failed: (.+)$/, "operation.resultMessage.parseExternalCommandsFailed", (match) => ({ error: match[1] })],
    [/^Serialize external commands failed: (.+)$/, "operation.resultMessage.serializeExternalCommandsFailed", (match) => ({ error: match[1] })],
    [/^Parse settings failed: (.+)$/, "operation.resultMessage.parseSettingsFailed", (match) => ({ error: match[1] })],
    [/^Serialize settings failed: (.+)$/, "operation.resultMessage.serializeSettingsFailed", (match) => ({ error: match[1] })],
    [/^Parse (English|Japanese|Quenya) language preset failed: (.+)$/, "operation.resultMessage.parseLanguagePresetFailed", (match) => ({ language: match[1], error: match[2] })],
    [/^Parse (.+) failed: (.+)$/, "operation.resultMessage.parseNamedSettingsFailed", (match) => ({ label: match[1], error: match[2] })],
    [/^Serialize (.+) failed: (.+)$/, "operation.resultMessage.serializeNamedSettingsFailed", (match) => ({ label: match[1], error: match[2] })],
    [/^Failed to read directory entry: (.+)$/, "operation.resultMessage.readDirectoryEntryFailed", (match) => ({ error: match[1] })],
    [/^Failed to (.+) '(.+)': (.+)$/, "operation.resultMessage.failedToPath", (match) => ({
      action: operationErrorActionLabel(match[1], t),
      path: match[2],
      error: match[3],
    })],
    [/^(.+) failed for '(.+)': (.+)$/, "operation.resultMessage.actionFailedForPath", (match) => ({
      action: operationErrorActionLabel(match[1], t),
      path: match[2],
      error: match[3],
    })],
    [/^(.+) failed for (.+): (.+)$/, "operation.resultMessage.actionFailedForPath", (match) => ({
      action: operationErrorActionLabel(match[1], t),
      path: match[2],
      error: match[3],
    })],
    [/^(.+) failed: (.+)$/, "operation.resultMessage.actionFailed", (match) => ({
      action: operationErrorActionLabel(match[1], t),
      error: match[2],
    })],
  ];

  for (const [pattern, id, values] of dynamicPatterns) {
    const match = message.match(pattern);
    if (!match) continue;
    const translated = t(id, values(match));
    return translated === id ? null : translated;
  }
  return null;
}

export function operationResultStatus(label: string, result: FileOperationResult, t: Translate = fallbackTranslate): string {
  const statusLabel = result.canceled ? t("operation.resultCanceledLabel", { label }) : label;
  return t("operation.resultStatus", {
    label: statusLabel,
    succeeded: result.succeeded.length,
    failed: result.failed.length,
  });
}

export function operationResultItemMessage(item: FileOperationResultItem, t: Translate = fallbackTranslate): string {
  if (item.messageId) {
    const translated = t(item.messageId, item.messageValues ?? {});
    if (translated !== item.messageId) return translated;
  }
  return translateLegacyOperationMessage(item.message, t) ?? item.message;
}

export function operationResultTerminalLines(
  label: string,
  result: FileOperationResult,
  succeededPreviewLimit = 10,
  t: Translate = fallbackTranslate,
): string[] {
  const lines = [""];
  for (const item of result.failed) {
    lines.push(t("operation.terminalFailed", { path: item.path || "-", message: operationResultItemMessage(item, t) }));
  }
  for (const item of result.succeeded.slice(0, succeededPreviewLimit)) {
    lines.push(t("operation.terminalOk", { path: item.path || "-", message: operationResultItemMessage(item, t) }));
  }
  if (result.succeeded.length > succeededPreviewLimit) {
    lines.push(t("operation.terminalOkMore", { count: result.succeeded.length - succeededPreviewLimit }));
  }
  lines.push(t("operation.terminalSummary", { status: operationResultStatus(label, result, t) }));
  return lines;
}
