import assert from "node:assert/strict";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

import { operationResultItemMessage } from "../src/routes/operationResultModel";
import { createTranslator } from "../src/routes/localization";
import type { LanguageSettings } from "../src/routes/types";

const japaneseSettings = JSON.parse(readFileSync("docs/examples/language.ja.json", "utf8")) as LanguageSettings;
const ja = createTranslator(japaneseSettings);

function rustFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    const stat = statSync(path);
    if (stat.isDirectory()) return rustFiles(path);
    if (!path.endsWith(".rs") || path.endsWith("main.rs") || path.endsWith("test_support.rs")) return [];
    return [path];
  });
}

function stripRustTestModule(source: string): string {
  return source.replace(/#\[cfg\(test\)\]\s*mod tests\s*\{[\s\S]*$/m, "");
}

function isUserFacingRustTemplate(template: string): boolean {
  return (
    /[A-Za-z]/.test(template) &&
    /(failed|Failed|required|exists|unsupported|Unsupported|not|Not|Cannot|cannot|No |Invalid|unknown|Unknown|empty|resolved|succeeded|completed|created|Deleted|Moved|Renamed|Copied|Uploaded|Downloaded|Extracted|changed|Changed|removed|Removed|target|Target|Destination|Archive|SFTP|SSH|Terminal|Mode|Name|Path|Config|Home|Safe|Git|Open|Read|Write|Create|Parse|Serialize|Finish|Flush|Resize|Launch|Add|Set)/.test(template)
  );
}

function extractedRustMessageTemplates(): string[] {
  const patterns = [
    /return Err\((?:format!\()?"([^"]+)"/g,
    /map_err\([\s\S]{0,120}?format!\("([^"]+)"/g,
    /message:\s*(?:format!\()?"([^"]+)"/g,
    /format_io_error\("([^"]+)"/g,
  ];
  const templates = new Set<string>();
  for (const file of rustFiles("src-tauri/src")) {
    const source = stripRustTestModule(readFileSync(file, "utf8"));
    for (const pattern of patterns) {
      for (const match of source.matchAll(pattern)) {
        if (isUserFacingRustTemplate(match[1])) templates.add(match[1]);
      }
    }
  }
  return Array.from(templates).sort();
}

const expectedBackendSourceTemplates = [
  "Add SSH host key failed: {error}",
  "Add zip file failed for '{}': {error}",
  "Archive created with {} item(s).",
  "Archive entry is a directory: {normalized_inner}",
  "Archive entry path is empty.",
  "Archive extraction exceeded the 100,000 entry limit.",
  "Archive extraction exceeded the 64 GiB expanded size limit.",
  "Archive image reader task failed: {error}",
  "Archive links are not allowed for extraction.",
  "Archive listing exceeded the 100,000 entry limit.",
  "Archive listing task failed: {error}",
  "Archive special entries are not allowed for extraction.",
  "Archive text viewer task failed: {error}",
  "Cannot create an archive inside a selected source directory.",
  "Change SFTP mode failed for '{remote_path}': {error}",
  "Changed Windows attributes.",
  "Changed mode to {:o}.",
  "Changed remote mode to {:o}.",
  "Clone PTY reader failed: {error}",
  "Copied to '{}'.",
  "Create SFTP directory failed for '{normalized}': {error}",
  "Create SFTP directory failed: {error}",
  "Create SFTP file failed for '{write_remote_path}': {error}",
  "Create SFTP file failed: {error}",
  "Create SSH session failed: {error}",
  "Delete SFTP file failed for '{remote_path}': {error}",
  "Deleted permanently from SFTP.",
  "Deleted permanently.",
  "Destination already exists.",
  "Destination already exists: '{destination}'",
  "Destination already exists: '{remote_destination}'",
  "Destination already exists: '{remote_path}'",
  "Destination already exists: '{}'",
  "Detailed diff task failed: {error}",
  "Directory created on SFTP.",
  "Directory created.",
  "Directory listing task failed: {error}",
  "Downloaded to '{}'.",
  "External command id is required.",
  "External command name is required: {}",
  "Extracted to '{}'.",
  "Failed to read directory entry: {error}",
  "File created on SFTP.",
  "File created.",
  "File operation task failed: {error}",
  "Finish gzip stream failed: {error}",
  "Finish tar entries failed: {error}",
  "Finish tar.gz archive failed: {error}",
  "Finish zip archive failed: {error}",
  "Flush terminal failed: {error}",
  "Git status task failed: {error}",
  "Image reader task failed: {error}",
  "Invalid name regex: {error}",
  "Launch text editor failed: {error}",
  "Local favorite id is required.",
  "Local favorite name is required.",
  "Local favorite was not found: {trimmed_id}",
  "Local target has no file name.",
  "Mixed SFTP connections in one chmod job are not supported.",
  "Mixed SFTP connections in one copy job are not supported.",
  "Mixed SFTP connections in one delete job are not supported.",
  "Mode must be an octal value like 644, 755, or 0755.",
  "Move to Trash failed for '{}': {error}",
  "Moved to '{}'.",
  "Moved to Trash.",
  "Name contains characters that are invalid on Windows.",
  "Name is reserved on Windows.",
  "Name must not contain NUL characters.",
  "Name must not contain path separators.",
  "Name must not end with a space or period on Windows.",
  "No Windows attribute changes were requested.",
  "No archive sources were resolved.",
  "No socket address resolved for {host}:{port}",
  "No target was resolved.",
  "Not a regular file: '{}'",
  "Not a tar archive: '{}'",
  "Open PTY failed: {error}",
  "Open PTY writer failed: {error}",
  "Open SFTP file failed for '{remote_path}': {error}",
  "Open SSH known_hosts store failed: {error}",
  "Open preferences failed: {error}",
  "Parse English language preset failed: {error}",
  "Parse Japanese language preset failed: {error}",
  "Parse Quenya language preset failed: {error}",
  "Parse external commands failed: {error}",
  "Parse location profiles failed: {error}",
  "Parse mode failed: {error}",
  "Parse settings failed: {error}",
  "Parse {label} failed: {error}",
  "Path is empty.",
  "Read SFTP directory failed for '{remote_path}': {error}",
  "Read SFTP directory failed: {error}",
  "Read SFTP metadata failed for '{remote_path}': {error}",
  "Read archive entries failed: {error}",
  "Read archive entry bytes failed: {error}",
  "Read archive entry failed: {error}",
  "Read archive entry path failed: {error}",
  "Read archive failed: {error}",
  "Read copy stream failed: {error}",
  "Refresh completed.",
  "Remove SFTP directory failed for '{remote_path}': {error}",
  "Remove empty SFTP directory failed for '{remote_path}': {error}",
  "Remove empty SFTP file failed for '{remote_path}': {error}",
  "Removed empty SFTP directory.",
  "Removed empty SFTP file.",
  "Removed empty directory.",
  "Removed empty file.",
  "Rename SFTP entry failed for '{remote_path}': {error}",
  "Renamed to '{}'.",
  "Resize terminal failed: {error}",
  "Resolve SFTP host failed: {error}",
  "Run git rev-parse failed: {error}",
  "Run git status failed: {error}",
  "SFTP chmod requires SFTP targets.",
  "SFTP connection is busy or unavailable: {connection_id}",
  "SFTP connection succeeded.",
  "SFTP connection task failed: {error}",
  "SFTP copy requires a local/SFTP source and destination.",
  "SFTP delete requires SFTP targets.",
  "SFTP directory listing task failed: {error}",
  "SFTP file creation requires an SFTP destination.",
  "SFTP host is required.",
  "SFTP listing exceeded the 100,000 entry limit.",
  "SFTP mkdir requires an SFTP destination.",
  "SFTP password is required.",
  "SFTP port must be between 1 and 65535.",
  "SFTP private key path is required.",
  "SFTP profile id is required.",
  "SFTP profile name is required.",
  "SFTP profile was not found: {trimmed_id}",
  "SFTP target has no file name.",
  "SFTP target has no parent directory.",
  "SFTP to SFTP copy is not implemented yet.",
  "SFTP username is required.",
  "SSH handshake failed: {error}",
  "SSH server host key type is unknown.",
  "Safe Mode loaded default settings after backing up current config files.",
  "Safe Mode startup failed: {error}",
  "Search profile id is required.",
  "Search profile name is required.",
  "Search profile was not found: {trimmed_id}",
  "Search task failed: {error}",
  "Serialize external commands failed: {error}",
  "Serialize location profiles failed: {error}",
  "Serialize settings failed: {error}",
  "Serialize {label} failed: {error}",
  "Set SFTP read timeout failed: {error}",
  "Set SFTP write timeout failed: {error}",
  "Spawn shell failed: {error}",
  "Start SFTP subsystem failed: {error}",
  "Target has no parent directory.",
  "Target is not an SFTP path.",
  "Terminal is not running.",
  "Text viewer task failed: {error}",
  "This SFTP file operation is not implemented yet.",
  "Undo can remove only an empty SFTP file.",
  "Undo can remove only an empty file.",
  "Unsupported SFTP authentication kind.",
  "Uploaded to '{}'.",
  "Uploading symlinks to SFTP is not implemented yet.",
  "Write copy stream failed: {error}",
  "Write terminal failed: {error}",
  "read editor target",
  "read empty file metadata",
  "read symlink target metadata",
  "remove empty directory",
  "remove empty file",
  "{label} authentication failed.",
  "{label} password authentication failed: {error}",
  "{label} path does not exist: {}",
  "{label} private key authentication failed: {error}",
];

const backendMessages = [
  "This SFTP file operation is not implemented yet.",
  "Refresh completed.",
  "SFTP to SFTP copy is not implemented yet.",
  "SFTP copy requires a local/SFTP source and destination.",
  "Target is not an SFTP path.",
  "Mixed SFTP connections in one copy job are not supported.",
  "SFTP target has no file name.",
  "Local target has no file name.",
  "SFTP delete requires SFTP targets.",
  "Deleted permanently from SFTP.",
  "No target was resolved.",
  "SFTP target has no parent directory.",
  "Requested name is the current name.",
  "SFTP mkdir requires an SFTP destination.",
  "Destination already exists.",
  "Directory created on SFTP.",
  "SFTP file creation requires an SFTP destination.",
  "File created on SFTP.",
  "SFTP chmod requires SFTP targets.",
  "Removed empty SFTP directory.",
  "Undo can remove only an empty SFTP file.",
  "Removed empty SFTP file.",
  "Target has no parent directory.",
  "Changed Windows attributes.",
  "Deleted permanently.",
  "Moved to Trash.",
  "Directory created.",
  "File created.",
  "Removed empty directory.",
  "Undo can remove only an empty file.",
  "Removed empty file.",
  "No archive sources were resolved.",
  "Archive name must end with .zip, .tar, .tar.gz, or .tgz.",
  "Cannot create an archive inside a selected source directory.",
  "Archive links are not allowed for extraction.",
  "Archive special entries are not allowed for extraction.",
  "Archive entry path is empty.",
  "Archive creation canceled.",
  "Archive extraction canceled.",
  "Archive extraction exceeded the 100,000 entry limit.",
  "Archive extraction exceeded the 64 GiB expanded size limit.",
  "Archive listing exceeded the 100,000 entry limit.",
  "Directory listing exceeded the 100,000 entry limit.",
  "SFTP listing exceeded the 100,000 entry limit.",
  "Directory listing task failed: denied",
  "Archive listing task failed: denied",
  "SFTP directory listing task failed: denied",
  "Search task failed: denied",
  "Detailed diff canceled.",
  "Search min size must be less than or equal to max size",
  "Search modified-after must be less than or equal to modified-before",
  "Unsupported search kind.",
  "Unsupported hidden search mode.",
  "Unsupported readonly search mode.",
  "SFTP host is required.",
  "SFTP port must be between 1 and 65535.",
  "SFTP username is required.",
  "SFTP password is required.",
  "SFTP private key path is required.",
  "Unsupported SFTP authentication kind.",
  "SFTP connection state is unavailable.",
  "SSH server host key type is unknown.",
  "SSH server host key is unavailable.",
  "Terminal is not running.",
  "Terminal state lock poisoned.",
  "Safe Mode state lock failed.",
  "Home directory could not be resolved.",
  "Home directory could not be resolved for known_hosts.",
  "Config directory could not be resolved.",
  "Uploading symlinks to SFTP is not implemented yet.",
  "Path is empty.",
  "Destination path is not set.",
  "Name is not set.",
  "Mode is not set.",
  "Windows attribute expression is not set.",
  "Mode must be an octal value like 644, 755, or 0755.",
  "No Windows attribute changes were requested.",
  "Attribute values must be on, off, or keep.",
  "Supported Windows attributes are readonly/r and hidden/h.",
  "Name must not contain path separators.",
  "Name must not contain NUL characters.",
  "Name contains characters that are invalid on Windows.",
  "Name is reserved on Windows.",
  "Name must not end with a space or period on Windows.",
  "Search profile name is required.",
  "Local favorite name is required.",
  "SFTP profile name is required.",
  "SFTP profile id is required.",
  "Local favorite id is required.",
  "Search profile id is required.",
  "External command id is required.",
  "Archive entry has no file name.",
  "Copied to '/tmp/example.txt'.",
  "Moved to '/tmp/example.txt'.",
  "Renamed to '/tmp/example.txt'.",
  "Downloaded to '/tmp/example.txt'.",
  "Uploaded to '/remote/example.txt'.",
  "Extracted to '/tmp/example'.",
  "Destination already exists: '/tmp/example.txt'",
  "Changed mode to 644.",
  "Changed remote mode to 644.",
  "Archive created with 2 item(s).",
  "SFTP connection is busy or unavailable: session-1",
  "SFTP connection is not available: session-1",
  "Start SFTP subsystem failed: denied",
  "Rename SFTP entry failed for '/remote/old.txt': denied",
  "Change SFTP mode failed for '/remote/file.txt': denied",
  "Delete SFTP file failed for '/remote/file.txt': denied",
  "Create SFTP directory failed: denied",
  "Create SFTP file failed: denied",
  "Create SFTP directory failed for '/remote/docs': denied",
  "Create SFTP file failed for '/remote/file.txt': denied",
  "Remove empty SFTP directory failed for '/remote/docs': denied",
  "Remove empty SFTP file failed for '/remote/file.txt': denied",
  "Read SFTP metadata failed for '/remote/file.txt': denied",
  "Read SFTP directory failed for '/remote/docs': denied",
  "Open SFTP file failed for '/remote/file.txt': denied",
  "Write SFTP file failed for '/remote/file.txt.part': denied",
  "Finalize SFTP part file failed for '/remote/file.txt.part': denied",
  "Remove SFTP directory failed for '/remote/docs': denied",
  "Move to Trash failed for '/tmp/file.txt': denied",
  "Read archive failed: corrupt",
  "Read archive entries failed: corrupt",
  "Read archive entry failed: corrupt",
  "Read archive entry path failed: corrupt",
  "Read archive entry bytes failed: corrupt",
  "Add zip directory failed for '/tmp/docs': denied",
  "Add zip file failed for '/tmp/file.txt': denied",
  "Finish zip archive failed: denied",
  "Finish tar.gz archive failed: denied",
  "Finish gzip stream failed: denied",
  "Finish tar entries failed: denied",
  "Open PTY failed: unavailable",
  "Open PTY writer failed: unavailable",
  "Spawn shell failed: unavailable",
  "Clone PTY reader failed: unavailable",
  "Write terminal failed: unavailable",
  "Flush terminal failed: unavailable",
  "Resize terminal failed: unavailable",
  "Image reader task failed: unsupported",
  "Archive image reader task failed: unsupported",
  "Text viewer task failed: unsupported",
  "Archive text viewer task failed: unsupported",
  "No socket address resolved for example.com:22",
  "Unsupported archive type: '/tmp/file.bin'",
  "Not a tar archive: '/tmp/file.zip'",
  "Destination has no file name: '/tmp'",
  "Archive source has no file name: '/tmp'",
  "Archive destination has no parent: '/tmp/archive.zip'",
  "Archive destination parent cannot be resolved: '/tmp/missing'",
  "Source has no file name: '/tmp'",
  "Destination has no parent: '/tmp/example.txt'",
  "Archive entry has an unsafe path: '../evil.txt'",
  "Archive entry is a directory: docs/",
  "Invalid name regex: unclosed group",
  "SFTP profile was not found: demo",
  "Local favorite was not found: demo",
  "Search profile was not found: demo",
  "Invalid archive entry path: ../evil.txt",
  "Unsupported image extension: .webp",
  "Not a regular file: '/tmp/docs'",
  "Unknown language preset: xx",
  "Temporary archive already exists: '/tmp/archive.zip.part'",
  "SFTP part file already exists: '/remote/file.txt.part'",
  "Extracted destination already exists: '/tmp/readme.txt'",
  "Archive entry was not found: '/tmp/archive.zip::/docs/readme.txt'",
  "Text editor target must be a local file: /tmp/docs",
  "Path must resolve to a local absolute path: ../demo",
  "Search root is not a directory: /tmp/file.txt",
  "Local favorite path is not a directory: /tmp/file.txt",
  "Git root could not be resolved for /tmp.",
  "git status failed.",
  "git status failed: not a git repository",
  "git rev-parse failed: not a git repository",
  "left path does not exist: /tmp/missing",
  "right path is not a directory: /tmp/file.txt",
  "Terminal cwd is not a directory: '/tmp/file.txt'",
  "External command name is required: demo",
  "External command template is required: demo",
  "External command argumentMode must be args, repeat, or join: demo",
  "Safe Mode startup failed: denied",
  "test private key path is required.",
  "test private key file does not exist: /tmp/key",
  "test private key authentication failed: denied",
  "test password authentication failed: denied",
  "test authentication failed.",
  "SSH host key mismatch for example.com:22. Check /home/me/.ssh/known_hosts before connecting.",
  "SSH known_hosts check failed for example.com:22 using /home/me/.ssh/known_hosts.",
  "Read SSH known_hosts failed (/home/me/.ssh/known_hosts): denied",
  "Create SSH known_hosts directory failed (/home/me/.ssh): denied",
  "Write SSH known_hosts failed (/home/me/.ssh/known_hosts): denied",
  "Connect to SFTP host failed for example.com:22. Tried: 192.0.2.1:22 (timeout)",
  "Create SSH session failed: denied",
  "Resolve SFTP host failed: denied",
  "Open SSH known_hosts store failed: denied",
  "Read SFTP directory failed: denied",
  "Parse location profiles failed: invalid json",
  "Serialize location profiles failed: denied",
  "Parse external commands failed: invalid json",
  "Serialize external commands failed: denied",
  "Parse settings failed: invalid json",
  "Serialize settings failed: denied",
  "Parse Japanese language preset failed: invalid json",
  "Parse appearance settings failed: invalid json",
  "Serialize appearance settings failed: denied",
  "Failed to read directory entry: denied",
  "Failed to resolve archive destination parent '/tmp/missing': denied",
  "read symlink target metadata failed for '/tmp/link': denied",
  "read editor target failed for '/tmp/docs': denied",
  "Add SSH host key failed: denied",
  "SFTP connection task failed: timeout",
  "SSH handshake failed: refused",
  "Set SFTP read timeout failed: denied",
  "Set SFTP write timeout failed: denied",
  "File operation task failed: denied",
  "Read copy stream failed: denied",
  "Write copy stream failed: denied",
  "Detailed diff task failed: canceled",
  "Git status task failed: denied",
  "Launch text editor failed: denied",
  "Open preferences failed: denied",
];

assert.deepEqual(
  extractedRustMessageTemplates(),
  expectedBackendSourceTemplates,
  "Rust user-facing backend message templates should be represented in backend localization coverage.",
);

for (const message of backendMessages) {
  assert.notEqual(
    operationResultItemMessage({ path: "", message }, ja),
    message,
    `backend message must be localizable: ${message}`,
  );
}
